### ISSUE TITLE
Tika Python not working for Java 1.8

### ISSUE THREAD

**Issue by anirbanmishra** [chrismattmann/tika-python#101]
As a part of my work I am supposed to call tika parser to get the contents of file in XHTML format and then feed it to the Grobid Quantities tool to get measurements details for each file. I found that Grobid quantities worked on Java 1.8 so I updated my java version to 1.8. At this stage the tika-python failed to work. Can some one please check if Tika-python works with java 1.8 because as soon as I reverted back to 1.7 it started working again.

**Comment by yashtanna93** [comment]
@anirbanmishra tika-python is working with java 1.8 on my system.
I am using Kubuntu and the java version is
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by chrismattmann** [comment]
i also have 1.8 and it works OK for me @anirbanmishra can you please confirm? I'm closing for now since it works for both myself and @yashtanna93
