### ISSUE TITLE
Update tika-python in accordance with changes in response to TIKA-1982

### ISSUE THREAD

**Issue by Ph-St** [chrismattmann/tika-python#103]
Should [TIKA-1982](https://issues.apache.org/jira/browse/TIKA-1982) be implemented such that the detected language will be available form the /rmeta endpoint, tika-python probably needs updating so that the detected language is available there as well.

**Comment by chrismattmann** [comment]
pushing to 1.15 since TIKA-1982 hasn't been addressed yet.

**Comment by chrismattmann** [comment]
doesn't look like anyone will provide a PR for this it's been years. Closing. If someone wants to put in a PR for this please do.
