### ISSUE TITLE
Add modules in tika-server classpath while creating instance of tika-python

### ISSUE THREAD

**Issue by smadha** [chrismattmann/tika-python#107]
To use advanced capabilities of Tika like NER Parser, GeoTopicParser, CTakes we need to modify  classpath while bringing up tika-server. classpath can be appended in below lines of code -

https://github.com/chrismattmann/tika-python/blob/69f4a8e321e40ff068ead25756219bfa966139eb/tika/tika.py#L351

**Comment by chrismattmann** [comment]
Hi @smadha it looks like #110 helps us here.
