### ISSUE TITLE
Create a new version of tika-python that binds to TikaJAXRS and get rid of JCC

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-python#11]
Tika's JAX-RS REST library is a very stable platform in lockstep with Tika development. I would like to rewrite and add to tika-python basically all the functionality that is provided by Tika JAX-RS here:

http://wiki.apache.org/tika/TikaJAXRS

Then I could get rid of the JCC dependencies and make this a heck of a lot easier to install.

**Comment by ahmadia** [comment]
In process in https://github.com/chrismattmann/tika-python/tree/tika-rest

**Comment by chrismattmann** [comment]
complete!
