### ISSUE TITLE
not pip installable

### ISSUE THREAD

**Issue by aterrel** [chrismattmann/tika-python#12]
The current setup.py doesn't follow python packaging authority standards making it not pip installable.  https://packaging.python.org/en/latest/

**Comment by aterrel** [comment]
@chrismattmann feel free to assign this issue to me, I will try to submit a patch later this week.

**Comment by chrismattmann** [comment]
yay @aterrel thanks for fixy, will do

**Comment by chrismattmann** [comment]
done!

**Comment by ahmadia** [comment]
@aterrel - Do you still want this?

**Comment by chrismattmann** [comment]
It is now! :) +1
