### ISSUE TITLE
Tika connection issue

### ISSUE THREAD

**Issue by bainadeashish** [chrismattmann/tika-python#121]
I am getting below error on Azure Web app using below below code
from tika import parser
text = parser.from_file(r"D:\home\test\vikaspatil1.doc")
error i am getting below error
HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions',))

**Comment by chrismattmann** [comment]
Hi @bainadeashish this looks like an issue where your tika server wasn't running. Please open new issue if problem persists.

**Comment by priyanshujain** [comment]
@chrismattmann  In my case same error is there and but tika server is running at port 9998.

**Comment by chrismattmann** [comment]
@priyanshujain can you please confirm that the server is running. For example what does curl http://localhost:9998 return?
