### ISSUE TITLE
Can't Read Arabic file names

### ISSUE THREAD

**Issue by AhmadSawalhah** [chrismattmann/tika-python#124]
@chrismattmann 
problem in reading files if its name is Arabic
try this file name ( احمد.docx)  , it give me this error

`File "C:\Python34\lib\http\client.py", line 1109, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 21-27: ordinal not in range(256)
`
when I just change the name to english, it works fine
thanks

**Comment by chrismattmann** [comment]
I'll check it out @AhmadSawalhah but it may have to come in 1.15

**Comment by chrismattmann** [comment]
in your program can you force the encoding *before* calling Tika?

**Comment by chrismattmann** [comment]
closing this as there is a current work-around. Just convert file name to English, then run. If you can answer my questions in the future feel free to open a new issue and cite this.
