### ISSUE TITLE
Is there a way to limit the content being parsed ?

### ISSUE THREAD

**Issue by attibalazs** [chrismattmann/tika-python#127]
I would like to limit the content returned by Tika to the first 1000 characters ? Is there a way to do this using your library.

Thanks for your awesome library and all the hard work for making it easy to talk to Tika from Python.

**Comment by chrismattmann** [comment]
thank you @attibalazs for your issue! Can you just take the return from parser.from_file()[:1000] like that?

**Comment by attibalazs** [comment]
Yes that`s how I was doing it, but it was very slow. Tika will parse the whole document and then only return the fist 1000 characters which isn`t very efficient. I was looking for a way  to tell Tika that it doesn`t need to go through the whole document. I ended up writing my own parsers in the end.

**Comment by chrismattmann** [comment]
Got it thanks @attibalazs . I don't have time to work on this now, so if you have time in the future please share your work arounds and I will link to them.
