### ISSUE TITLE
Using a local .jar file?

### ISSUE THREAD

**Issue by nickstanisha** [chrismattmann/tika-python#128]
If I already have a tika .jar file downloaded stored, can I tell tika-python to always use use the one I have and never look to maven or its cache directory?

The best solution I could come up with is to specify the local .jar as a `file:///...` URI and rely on tika-python's downloading and caching behavior to find and use it, but that seems a bit indirect for something like this.

**Comment by chrismattmann** [comment]
the file:// strategy is a great one @nickstanisha - would love to see a page on the wiki that shows how you did it. I think it's great for now.
