### ISSUE TITLE
Using tika-python in AWS lambda

### ISSUE THREAD

**Issue by braunreyes** [chrismattmann/tika-python#129]
Would you recommend using this package as part of a text extraction pipeline in aws lambda?  Has anyone tried this before?  I guess memory/compute would be my main concern.  Looks like open jdk 8 may be installed for python runtime.  Any feedback would be greatly appreciated.

**Comment by chrismattmann** [comment]
hey @braunreyes - looking at the description of Lambda it seems like tika-python would be a good candidate for it. It will manage invocation of JDK, etc. but I don't see that as overly imposing.

**Comment by chrismattmann** [comment]
question answered, if someone does this I would love to hear about it!

**Comment by HollywoodMarks** [comment]
I am working on this right now.
