### ISSUE TITLE
tika-python with Tesseract OCR parser

### ISSUE THREAD

**Issue by alonsopg** [chrismattmann/tika-python#130]
Is it possible to set Tesseract OCR parser with this wrapper?.

**Comment by chrismattmann** [comment]
Hi - what do you mean set? If you mean configure it yes just a little kludgy. See the readme example for how to turn on geo topic parser as an example.

**Comment by alonsopg** [comment]
Thanks @chrismattmann, I tried to check the readme. However, I did not understand how to configure the wrapper with tessaract. Could you provide some example?.

**Comment by chrismattmann** [comment]
sure @alonsopg I'll provide an example shortly. Sorry about that.

**Comment by alonsopg** [comment]
Thanks @chrismattmann !

**Comment by alonsopg** [comment]
Hi @chrismattmann I'm still stucked with the Tesseract OCR parser is there any other reference where I can learn how to set such parser?. Thanks!

**Comment by chrismattmann** [comment]
Hi @alonsopg basically you want to check out: http://wiki.apache.org/tika/TikaOCR, and then kill the existing Tika REST server (if it's running). Once tesseract is on your path, Tika-Python should pick it up automatically. Try that.

**Comment by chrismattmann** [comment]
ping @alonsopg

**Comment by alonsopg** [comment]
Thanks @chrismattmann , I will try to do it.

**Comment by chrismattmann** [comment]
did you try @alonsopg ?

**Comment by chrismattmann** [comment]
going to close this out - if you find the same problem or if the docs weren't helpful please open a new issue.
