### ISSUE TITLE
Selecting output content type

### ISSUE THREAD

**Issue by lamb003** [chrismattmann/tika-python#131]
Firstly thanks for this project @chrismattmann. 

I've been working with it for a short time now. And really like that I can interface with tika this way. 
Although I'd like to ask for/suggest an enhancement. 

Tika seems to allow for an output content in text, xml and html. 
As per: https://wiki.apache.org/tika/TikaJAXRS#Recursive_Metadata_and_Content
Outputs as xml/html may be useful for targeting specific sections of the content. So my request is for a way to select the content output type. 

If this is something you already support, and I just haven't been able to figure out how to do it. please point me in the right direction.

**Comment by lamb003** [comment]
I have just seen issue #65 and that this is supported. 
Closing this ticket.

**Comment by chrismattmann** [comment]
Thanks!

**Comment by chrismattmann** [comment]
thanks @lamb003 appreciate it. I see too that you asked for some updated docs. If you have time can you document this feature and send me a PR for the README? Thanks.

**Comment by lamb003** [comment]
@chrismattmann sure, I will take a look at doing that.
