### ISSUE TITLE
Multiple instances of tika-python request write access to the same /tmp/tika.log file

### ISSUE THREAD

**Issue by gabriel-v** [chrismattmann/tika-python#133]
## The problem

[This line](https://github.com/chrismattmann/tika-python/blob/e67ecabefb2c08cd0ce0415f815551c802af95fd/tika/tika.py#L102) hardcodes the log file to `/tmp/tika.log`.

If multiple instances of tika-python are used by two different unix users, the second user that imports an instance of tika-python won't have write access to the log file created by the first user and the import will fail.

If, on the other hand, the instances are run by the same unix user, their log files will get truncated and/or mangled, which is undesirable.

## Workarounds

Possible workarounds without a fix are:

- Overwriting `os.environ['TMPDIR']` before import so [`tempfile.gettempdir()`](https://docs.python.org/2/library/tempfile.html#tempfile.gettempdir) gets the desired path.
- Monkeypatching [`tempfile.tempdir`](https://docs.python.org/2/library/tempfile.html#tempfile.tempdir) to obtain the same effect.

Both of them are undesirable as they introduce unneeded complexity on the client side.

## Solutions

There are two simple ways to fix this:

- use `tempfile.mkstemp(suffix='tika.log')`(docs: python [2](https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp), [3](https://docs.python.org/3.6/library/tempfile.html#tempfile.mkstemp)) to create the log file. This will raise an issue of backwards compatibility, because probably some users count on the log being in `/tmp/tika.log`.
- use an environment variable, say `TIKA_LOG_FILE`, for the `log_file` variable, if it's set. If it's not set, either use the above `tempfile.mkstemp()` to get a fresh log file, or use the hard-coded `/tmp/tika.log`.

What combination of these will make a good upstream solution?

**Comment by chrismattmann** [comment]
Thanks @gabriel-v appreciate you raising this issue. I like this option:

> use an environment variable, say TIKA_LOG_FILE, for the log_file variable, if it's set. If it's not set, either use the above tempfile.mkstemp() to get a fresh log file, or use the hard-coded /tmp/tika.log.

Would you like to send a PR for this?

**Comment by chrismattmann** [comment]
thank you really appreciate it @gabriel-v
