### ISSUE TITLE
Add documentations to methods

### ISSUE THREAD

**Issue by thammegowda** [chrismattmann/tika-python#136]
Current very few methods have documentation strings.

We need documentation to facilitate meta learning.

References for the format:
+ reST - PEP287 : https://www.python.org/dev/peps/pep-0287/
+ Discussions on Stackoverflow http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format

**Comment by chrismattmann** [comment]
thanks @thammegowda just mention which files you want to work on and we'll divide the work! 👍

**Comment by thammegowda** [comment]
Just a few methods exist in this code.  Leave this to me 💯 %
