### ISSUE TITLE
Resolve differences between tika-temp.py and tika/tika.py

### ISSUE THREAD

**Issue by ahmadia** [chrismattmann/tika-python#14]

**Comment by dongnizh** [comment]
Hi @ahmadia This is just the temp version of tika.py.
I have talked with @chrismattmann today, and I was thinking of the way by detecting the port to start service. I have done one on my local repo [https://github.com/dongnizh/tika-python/blob/tika-rest/tika/tika.py] and you can have a look at that one.  I am trying to test it stability right now.

**Comment by chrismattmann** [comment]
Completed!
