### ISSUE TITLE
Add support for SSL/TLS connection

### ISSUE THREAD

**Issue by frennkie** [chrismattmann/tika-python#140]
I have a host where I can't install Tika/Java and therefore I set up a dedicated Tika machine. On that machine I'm using nginx as a reverse proxy to forward the external port 8080 to the internal Tika port 9998 and this works fine. 

But now I would also like to encrypt the connection between my host and the Tika machine - which is easy on the server side as I just have to add SSL to the nginx configuration.

I see that tika-python (the client side) uses ``requests`` for making HTTP connections and I think it should not be too complicated to also support a Tika server url like `https://tika.example.com:8443`. 

Could this be implemented?

**Comment by chrismattmann** [comment]
Hi - have you tried using that HTTPS URL - dumb question - but thought I'd ask

**Comment by frennkie** [comment]
Yes, I tried it - unfortunately I did not record the error message. But this line https://github.com/chrismattmann/tika-python/blob/master/tika/tika.py#L544 indicates to me that `http:// ` is hardcoded.

If SSL/TLS can be supported then it would also be useful to be able to turn off verification (if needed) and to provide a custom CA bundle.

**Comment by frennkie** [comment]
Here is the (partial) trace:

```
Call stack:
  File "./otrs_faq_to_es.py", line 98, in <module>
    parsed_dict = parser.from_buffer(faq_attachment['content'], config.TIKA_URL)
  File "/usr/lib/python3.4/site-packages/tika/parser.py", line 34, in from_buffer
    {'Accept': 'application/json'}, False)
  File "/usr/lib/python3.4/site-packages/tika/tika.py", line 343, in callServer
    log.warning('Tika server returned status:', resp.status_code)
Message: 'Tika server returned status:'
Arguments: (400,)
```

```
HTTP/1.1 400 Bad Request                                                                                                                                            Server: nginx/1.4.6 (Ubuntu)                                                                                                                                                Date: Sun, 28 May 2017 18:42:54 GMT                                                                                                                                         Content-Type: text/html
Content-Length: 279                                                                                                                                                         Connection: close

[...]
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
[...]
```

I noticed that `checkTikaServer` is bypassed when `TikaClientOnly` is True.. but how would I set that?

**Comment by chrismattmann** [comment]
@frennkie can I see your code that is using tika-python? For example, when you use tika.TikaClientOnly = True, and then e.g., do:

```python
import tika
tika.TikaClientOnly = True
from tika import parser

parsed = parser.from_file('some file path', 'https://somehttpsurl')
```
In that case does it force HTTPS?

Another option you can try, set your environment variable `TIKA_SERVER_ENDPOINT` to `https://somehttpsurl' before starting python - does that fix it?

**Comment by frennkie** [comment]
> In that case does it force HTTPS?

Nope... Here is the Code which should be just as you are suggesting is:
https://github.com/frennkie/otrs_faq/blob/master/otrs_faq_to_es.py

**Comment by frennkie** [comment]
Setting config.TIKA_URL to `http://host:9080` works, `https://host:9443` doesn't.

**Comment by chrismattmann** [comment]
what about the environment variable @frennkie ?

**Comment by chrismattmann** [comment]
taken care of in #142 thank you @frennkie !
