### ISSUE TITLE
No method fro appending new metadata

### ISSUE THREAD

**Issue by antman1p** [chrismattmann/tika-python#145]
I cannot find a method for appending new metadata like FileName.

**Comment by chrismattmann** [comment]
Hi @antman1p I'm not sure exactly what you mean by appending new metadata? the parser interface for example returns a dictionary content parsed text content and metadata. You can do what you want with that returned struct? So that should be enough, right?

**Comment by antman1p** [comment]
I got it to work in my script with this line:
`parsed['metadata'].update({"FullFileName": str(file)}`
