### ISSUE TITLE
Unable to send header information for ocr

### ISSUE THREAD

**Issue by wingtips1** [chrismattmann/tika-python#146]
I’m using tika-python for a health care application to help extract text from medical documents.
At this time, cannot send header information to the tika server in Python to use with OCR.
 
For example in Postman, I can do:
PUT http://localhost:9998/tika

With headers:
Content-type: application/pdf
X-Tika-PDFOcrStrategy: ocr_only

If I don’t do this, many pdfs in the store of documents I am parsing will return with blank output. How do I implement these types of statements in with tika-python and with a dockerized Tika server?  

I can do this in tika-python:
parsed = parser.from_file('/path/to/file', 'http://localhost:9998/tika’)
Unfortunately, without sending the headers, most PDFs I have aren’t processed correctly and the output is blank.

**Comment by lvieirajr** [comment]
I also feel this pain on my use case so I created a PR to solve the problem: #154

**Comment by chrismattmann** [comment]
fixed in #154 thanks @lvieirajr
