### ISSUE TITLE
Command line tool's exit code is nonzero on success

### ISSUE THREAD

**Issue by maeb** [chrismattmann/tika-python#149]
_Environment: GNU/Linux Fedora 26 and python 2.7_

When i try to detect a language like `tika-python language file /tmp/text.txt` the return code is non-zero (1) on success.

The wrapper in `env/bin/tika-python` (installed by pip?) exits like `sys.exit(main())` and `main()` returns the result of `detectLanguage` which returns an array like `[(200, u'no')]`.

So the script is exited like `sys.exit([(200, u'no')]` resulting in an exit code of 1 on success.

**Comment by chrismattmann** [comment]
thanks @maeb What would you recommend as a way of addressing this? Thoughts? Do you have a PR in mind?

**Comment by chrismattmann** [comment]
ping @maeb

**Comment by chrismattmann** [comment]
hi @maeb let me know if you have a fix for this, otherwise I will likely go ahead and close it.

**Comment by maeb** [comment]
Hi @chrismattmann Sorry for the late answer.

I encountered this bug while trying out something at work and have unfortunately no time to implement a fix for this issue.

**Comment by chrismattmann** [comment]
Understood maybe when you get time send a PR and I'll look thanks!
