### ISSUE TITLE
parser interface for text extraction

### ISSUE THREAD

**Issue by lathakris** [chrismattmann/tika-python#152]
I have a little program to do the meta and text extraction from files (trying with PDF).  (file is the filename with complete path). I am using the parser interface. Took from the sample provided on this documentation. 

parsed = parser.from_file(file,  xmlContent=False)
print("****metadata****")
print(parsed["metadata"])
print("****content****")
print(parsed["content"])

The program is unable to print the content - below is the error. (it works with the unpack.from_file() interface, but that interface does not work with the zip files)

Could you please help, thank you very much. this python library is very useful, thank you!!

Traceback (most recent call last):
  File "parse.py", line 14, in <module>
    print(parsed["content"])
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 75-79: ordinal not in range(256)

**Comment by chrismattmann** [comment]
hi @lathakris can you try setting your python charset in the environment? for example, can you try to use unicode.encode and encode the result of parsed["content"] to utf-8 and then try printing it?

See: https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python

**Comment by lathakris** [comment]
Thank you for your quick response.
Let me give this a try. the unpack interface works fine not sure why. (just that it is not extracting text out of zip files)

parsed = unpack.from_file(file)
print("****metadata****")
print(parsed["metadata"])
print("****content****")
print(parsed["content"])

**Comment by lathakris** [comment]
when I export this environment variable on the console and run the program it works 
export PYTHONIOENCODING=utf8. default result seems to be utf8.

Thank you very much.

**Comment by chrismattmann** [comment]
awesome @lathakris can you update the README.md file and then send me a PR noting this? Thanks!

**Comment by lathakris** [comment]
Thank you. I think I have created a PR. Could you please check. Thank you.

https://github.com/chrismattmann/tika-python/pull/153

**Comment by chrismattmann** [comment]
thanks @lathakris committed!

**Comment by lathakris** [comment]
Thank you.
