### ISSUE TITLE
Parsed Content is none when I am trying to extract text from a image. 

### ISSUE THREAD

**Issue by ToniyaSundaram** [chrismattmann/tika-python#157]
parsed = parser.from_file('D:/PythonPrograms/sample.png', 'http://localhost:9996/')
parsed
>>> {'content': None, 'metadata': {'Chroma BackgroundColor': 'red=255, green=255, blue=255', 'Chroma BlackIsZero': 'true', 'Chroma ColorSpaceType': 'RGB', 'Chroma NumChannels': '4', 'Compression CompressionTypeName': 'deflate', 'Compression Lossless': 'true', 'Compression NumProgressiveScans': '1', 'Content-Type': 'image/png', 'Data BitsPerSample': '8 8 8 8', 'Data PlanarConfiguration': 'PixelInterleaved', 'Data SampleFormat': 'UnsignedIntegral', 'Dimension HorizontalPixelSize': '0.35273367', 'Dimension ImageOrientation': 'Normal', 'Dimension PixelAspectRatio': '1.0', 'Dimension VerticalPixelSize': '0.35273367', 'Document ImageModificationTime': 'year=2009, month=5, day=29, hour=20, minute=48, second=53', 'IHDR': 'width=550, height=287, bitDepth=8, colorType=RGBAlpha, compressionMethod=deflate, filterMethod=adaptive, interlaceMethod=none', 'Transparency Alpha': 'nonpremultipled', 'X-Parsed-By': ['org.apache.tika.parser.DefaultParser', 'org.apache.tika.parser.ocr.TesseractOCRParser', 'org.apache.tika.parser.image.ImageParser'], 'X-TIKA:parse_time_millis': '5101', 'bKGD bKGD_RGB': 'red=255, green=255, blue=255', 'height': '287', 'iCCP': 'profileName=ICC Profile, compressionMethod=deflate', 'pHYs': 'pixelsPerUnitXAxis=2835, pixelsPerUnitYAxis=2835, unitSpecifier=meter', 'resourceName': 'sample.png', 'tIME': 'year=2009, month=5, day=29, hour=20, minute=48, second=53', 'tiff:BitsPerSample': '8 8 8 8', 'tiff:ImageLength': '287', 'tiff:ImageWidth': '550', 'width': '550'}}

I tried this. any help will be much appreciated. Please help.

**Comment by chrismattmann** [comment]
What text are you expecting to be extracted? Can you show me the sample image? Do you have Tesseract installed and available on the tika-server classpath?

**Comment by chrismattmann** [comment]
no feedback since Sept, closing.
