### ISSUE TITLE
Consider better packaging for tika JAR file

### ISSUE THREAD

**Issue by ahmadia** [chrismattmann/tika-python#17]
* [ ] Brainstorm! (Chat with @chrismattmann?)
* [x] Implement!
* [x] ~~Test~~

**Comment by chrismattmann** [comment]
So far the existing mechanism works and I haven't been able to find a better setuptools recipe for dealing with JAR files. If we find one I think we can open a new one and reference this.

**Comment by aterrel** [comment]
http://shiningpanda.com/python-java-unified-build-process-14.html
