### ISSUE TITLE
extracting text from archive files

### ISSUE THREAD

**Issue by lathakris** [chrismattmann/tika-python#172]
Hi, 

I am using the parser interface of the tika-python library to extract text content from files.  (parser.from_file) I am running the tika server locally. 

How does this work for the text extraction from archive files - tgz, zip etc.  which contain multiple files inside them ? I see that the meta data is returned as a json list ? How about the content.  any specific way to identify this returned multiple files as opposed to one file ?

Thank you for your help.

**Comment by chrismattmann** [comment]
Thanks for your question @lathakris. Right now, the content is appended (as is the metadata, but it is collected in a list as you mention). For the text, it's appended, see: https://github.com/chrismattmann/tika-python/blob/master/tika/parser.py#L80 The thing is, it would be great to pull in the content handler interface from the Java side of Tika, but exposing that via the REST server isn't there yet. There is some [discussion](http://markmail.org/message/ssfjsv7zdi45h5w4) about it though, so I encourage you to participate there. Once we have content handler capabilities, we can expose that downstream here in Tika Python.

**Comment by lathakris** [comment]
Thank you very much for your response. I will check it out.

**Comment by lathakris** [comment]
just a question on this archive files text extraction, the unpack interface does not extract text out of archive files ? Is this expected ? (unpack.from_file() does not only parser.from_file() does)

Thank you.

**Comment by chrismattmann** [comment]
hi @lathakris yes, per [this page](http://wiki.apache.org/tika/TikaJAXRS].
