### ISSUE TITLE
Encoding problem in dedectType1

### ISSUE THREAD

**Issue by Patdue** [chrismattmann/tika-python#174]
When using detectType1 in [tika.py](https://github.com/chrismattmann/tika-python/blob/cb8cd4712bf2b74f90ee8b10683433ce0cfc132f/tika/tika.py) a UnicodeDecodeError is raised on line 459.

To fix the issue i changed 
```
status, response = callServer('put', serverEndpoint, service, open(path, 'r'),
            {
                'Accept': responseMimeType,
                'Content-Disposition': make_content_disposition_header(path)
            },
            verbose, tikaServerJar)
```
to 

```
status, response = callServer('put', serverEndpoint, service, open(path, 'rb'),
            {
                'Accept': responseMimeType,
                'Content-Disposition': make_content_disposition_header(path)
            },
            verbose, tikaServerJar)
```
(like in `parse1`).

I expect the issue to also occur for `detectLang1` and `doTranslate1`

**Comment by chrismattmann** [comment]
hi @Patdue can you please submit a PR to fix this in those interfaces and then make sure the tests pass? I'd be happy to commit it.
