### ISSUE TITLE
Failed to establish a new connection: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by srinidhinandakumar** [chrismattmann/tika-python#178]
I'm trying to use parser.from_file('file-path') and facing this issue.
I looked through other issues and found the following solutions:-
- killall java 
- check if port 9998 is free 
- check for firewall blocking 
- check if other tika instances are running on port 9998
But none of these resolve my problem.
Is there something else I'm missing out on?
<img width="996" alt="screen shot 2018-03-22 at 12 10 09 pm" src="https://user-images.githubusercontent.com/12572165/37792903-506f90dc-2dca-11e8-84c2-720dede4449b.png">
PS: I have java version 9.0.4 and python version 3.6.3

**Comment by chrismattmann** [comment]
java9 - Tika only works with java8....
