### ISSUE TITLE
How to use Tika to read a lot of PDF faster?

### ISSUE THREAD

**Issue by maximedrei** [chrismattmann/tika-python#181]
Hello,

I am discovering Tika because I was convinced that's faster than PDFminer when there is a lot of PDF to read. After checking, I realized that it's more than 6x slower then PDFMiner when I read 10 000 PDF one by one in a loop (with the following method from tika "parser.from_file('MyPdf.pdf')").

So I would like to know if there is another way to use Tika to be more efficient reading a lot of PDF at the same time. (Maybe using a batch mode if it exist?)

Many thanks for your help.

Best,
Max

**Comment by chrismattmann** [comment]
@maximedrei thanks for your question. I would recommend taking it upstream to dev@tika.apache.org. We don't really introduce any overhead at all in tika-python - it's just a REST call to Tika-Server, e.g., see [here](http://wiki.apache.org/tika/TikaJAXRS).
