### ISSUE TITLE
Chaning TIKA_SERVER_ENDPOINT

### ISSUE THREAD

**Issue by allison9y** [chrismattmann/tika-python#185]
Is there any way to change TIKA_SERVER_ENDPOINT to a new tika server which is slightly modified? I am able to pass it in parser but it would be better if I can change the server url permanently.

**Comment by chrismattmann** [comment]
Yep, see the `[TIKA_SERVER_ENDPOINT](https://github.com/chrismattmann/tika-python#environment-variables)` environment variable.
