### ISSUE TITLE
cant install because of: urllib.error.HTTPError: HTTP Error 403: SSL is required

### ISSUE THREAD

**Issue by Mahlss** [chrismattmann/tika-python#187]
![image](https://user-images.githubusercontent.com/18452963/42221868-94aab240-7ea1-11e8-95de-23e4054ae13f.png)
Getting this 403 error every time I try to install.
Things I have already done:
pip install tika
pip install tika-i https://pypi.python.org/simple/
downloading it from github and running python setup.py build and install
Updating pip
Using the url https://github.com/chrismattmann/tika-python/ when installing instead of just tika with pip
I know for a fact I have java.
I tried changing http to https in setup.py and THEN building it.
Same thing every time.

**Comment by chrismattmann** [comment]
sorry you need to install SSH with PIP. See here: https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi

**Comment by gittian** [comment]
I have tried the workaround but still it doesn't work, has there been any modifications because of python update?

**Comment by chrismattmann** [comment]
sorry this is a PIP issue with HTTPS and SSL....has nothing to do with Tika.

**Comment by weaming** [comment]
Follow above stackoverflow answers and still failed
