### ISSUE TITLE
In tika.py tika.startServer() String Port default breaks the formatting command on like 614-615

### ISSUE THREAD

**Issue by austynh** [chrismattmann/tika-python#194]
Hi. Not a huge issue, but I tried calling the startServer function with using default parameters and I encountered a string formatting issue on the command for line 615 of tika.py from the default port (the default port is str and int is expected). Feel free to close as this is not a big deal. I just wanted to make the issue known. I can easily get around the issue by passing in a port. 

Below is the error.
line 615, in startServer % (java_path, classpath, port, host) TypeError: %i format: a number is required, not str.

Thanks for the help. This is an awesome tool. 😃

**Comment by austynh** [comment]
I'll make a fork+pr.

**Comment by vc1492a** [comment]
Thanks @austynh! Fork+pr is a good idea, glad you're finding Tika-Python useful.
