### ISSUE TITLE
Password Protected Files

### ISSUE THREAD

**Issue by Piyush1416** [chrismattmann/tika-python#196]
If I got a file which is password protected, how do I parse it for metadata and content?
Given the fact that I have a password of the file.

**Comment by chrismattmann** [comment]
Check out some of the results here, in particular what system properties you would need to set. In Tika-Python you would set those before tika-python is called and your Java server is started so it picks them up.
https://www.google.com/search?q=tika+encrypted+pdf&oq=tika+encrypted+pdf&aqs=chrome..69i57j69i60j69i64.2199j0j4&sourceid=chrome&ie=UTF-8
