### ISSUE TITLE
position of text blocks

### ISSUE THREAD

**Issue by atefehkhoshnood** [chrismattmann/tika-python#205]
Hi @chrismattmann,
Do we have support for obtaining position of a text block in a pdf file using tika-python? I want to have the positions so I can have a measure of indentation.

Thanks,
Atefeh

**Comment by chrismattmann** [comment]
thanks for asking @atefehkhoshnood I think this should be handled upstream in [Tika Java](https://issues.apache.org/jira/browse/TIKA).
