### ISSUE TITLE
Open Document XHTML not valid

### ISSUE THREAD

**Issue by cgallay** [chrismattmann/tika-python#207]
I think this might be a bug with tika directly but when I try to parse a document generated from the Libre Office Suite (like an `.odt` document) and get the XHTML output, it seems to me like it's not well formatted according to the XHTML standard.

Particularly, I wanted to use [minidom](https://docs.python.org/2/library/xml.dom.minidom.html)'s parser from python to deal with the tika output, but I am getting `ExpatError: junk after document element: line 51, column 14`.

The python code to generate this `ExpatError` is quite simple:
```Python
parsed = parser.from_file('../docs/test.odt', xmlContent=True)
xmldoc = minidom.parseString(parsed['content'])
```

Did anyone ever exerpenced this ?

**Comment by chrismattmann** [comment]
hmmm, possible, but I think that this is upstream in the [Tika Java](http://issues.apache.org/jira/browse/TIKA) library itself. Please file there.

**Comment by cgallay** [comment]
I have found a workaround to this issue.
In fact `parsed['content']` contains multiple `<html>` tags at the root of the document. But `XML` require the root to be unique. Therefore splitting into multiple xml strings that you can feed to `minidom` solved the issue.

```python
import re
def split_str2xml(text):
    regex = re.compile(r"<html.*?>.*?</html>", re.DOTALL)
    matchs = regex.finditer(text)
    for m in matchs:
        yield m.group()
for xml in split_str2xml(parsed['content']):
    xmldoc = minidom.parseString(xml)
```

**Comment by chrismattmann** [comment]
@cgallay can you add this as a PR? maybe provide the above as a function in parser.py?
