### ISSUE TITLE
Tika parser is unable to startup [Warn Failed to see Startup Log...] 

### ISSUE THREAD

**Issue by frogeyedpeas** [chrismattmann/tika-python#211]
Primary Problem: whenever I try to instantiate the parser some error involving warning logs appears and the code just dies: 

```018-12-30 01:37:29,263 [MainThread  ] [WARNI]  Failed to see startup log message; retrying...```

And some external java process lives on in my dock, (I have screen shotted the icon and attached).

The exact code I have is the [following:]
<img width="88" alt="screen shot 2018-12-30 at 1 42 11 am" src="https://user-images.githubusercontent.com/5061556/50544968-3adc5000-0bd4-11e9-814d-fea6c1badad7.png">

``` 
     from tika import parser
     path='./pdfs/'
     raw = parser.from_file(path)  

```

I have tried running this code with SUDO, and updating my java version all to no avail.

System Details:
---

I'm using Mac OS X El Capital Version 10.11.5, with oh-my-zsh as my terminal
And python 3.6

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by bradyschaer** [comment]
I know this is closed, but how did you fix it? I am getting the same issue.

**Comment by LIU-Yinyi** [comment]
@bradyschaer hi, actually readme has mentioned the preset for environment variables.    
What you should do is to setup `TIKA_LOG_PATH` with a directory that owns **write-permissions**. 

e.g. :
```bash
# bash
export TIKA_LOG_PATH=/Users/to/my/dir/that/could/write
```

**Comment by MoishyVFX** [comment]
I'm having the same issue...
