### ISSUE TITLE
unpack not return server status

### ISSUE THREAD

**Issue by ori19939** [chrismattmann/tika-python#212]
in unpack.py if server have problem, the status not returned.
fix:
`def _parse(tarOutput):
    parsed = {}
    if not tarOutput:
        return parsed
    elif tarOutput[1] is None or tarOutput[1] == b"":
        parsed["status"] = tarOutput[0]
        return parsed

    tarFile = tarfile.open(fileobj=BytesIO(tarOutput[1]))

    # get the member names
    memberNames = list(tarFile.getnames())

    # extract the metadata
    metadata = {}
    if "__METADATA__" in memberNames:
        memberNames.remove("__METADATA__")

        metadataMember = tarFile.getmember("__METADATA__")
        if not metadataMember.issym() and metadataMember.isfile():
            metadataFile = _text_wrapper(tarFile.extractfile(metadataMember))
            metadataReader = csv.reader(metadataFile)
            for metadataLine in metadataReader:
                # each metadata line comes as a key-value pair, with list values
                # returned as extra values in the line - convert single values
                # to non-list values to be consistent with parser metadata
                assert len(metadataLine) >= 2

                if len(metadataLine) > 2:
                    metadata[metadataLine[0]] = metadataLine[1:]
                else:
                    metadata[metadataLine[0]] = metadataLine[1]

    # get the content
    content = ""
    if "__TEXT__" in memberNames:
        memberNames.remove("__TEXT__")

        contentMember = tarFile.getmember("__TEXT__")
        if not contentMember.issym() and contentMember.isfile():
            if version_info.major >= 3:
                content = _text_wrapper(tarFile.extractfile(contentMember), encoding='utf8').read()
            else:
                content = tarFile.extractfile(contentMember).read().decode('utf8')

    # get the remaining files as attachments
    attachments = {}
    for attachment in memberNames:
        attachmentMember = tarFile.getmember(attachment)
        if not attachmentMember.issym() and attachmentMember.isfile():
            attachments[attachment] = tarFile.extractfile(attachmentMember).read()
    parsed["status"] = tarOutput[0]
    parsed["content"] = content
    parsed["metadata"] = metadata
    parsed["attachments"] = attachments

    return parsed`

**Comment by chrismattmann** [comment]
please submit a PR for this.

**Comment by chrismattmann** [comment]
if there is interest, please submit a PR
