### ISSUE TITLE
Feature Request: Timeout on all requests

### ISSUE THREAD

**Issue by AlexMayle** [chrismattmann/tika-python#217]
For production, a timeout on requests is almost always necessary. I've forked the library and added it to the calls I use. I think a lot of others would find it beneficial to have an optional timeout parameter accepted by all public methods which end up sending a request to the Tika REST server. 

The requests library supports an optional timeout parameter. The implementation would be as trivial as passing the argument from the high-level public methods, through the callServer method, and finally passing it to the verbFn call.

**Comment by chrismattmann** [comment]
hi @AlexMayle absolutely interested in a PR for this, with sensible defaults and the ability to override.
