### ISSUE TITLE
Tika REST does not start in background

### ISSUE THREAD

**Issue by karthikkrishnanv** [chrismattmann/tika-python#218]
Per doc, "To use this library, you need to have Java 7+ installed on your system as tika-python starts up the Tika REST server in the background."

But the background server does not start (tried 2.7 and 3.x python) during installation and there are no failures. Any idea ?

**Comment by chrismattmann** [comment]
check your tmp directory for tika-server.log or tika.log. What do they say? Also what platform/OS, and Java version and Python version do you have installed?

**Comment by karthikkrishnanv** [comment]
After digging around, it looks like the server does start after the first API call (downloads jar and starts it). Closing the ticket as it works now.
