### ISSUE TITLE
Deploying project and database to heroku

### ISSUE THREAD

**Issue by Jonnoramo** [chrismattmann/tika-python#219]
![image](https://user-images.githubusercontent.com/26510376/52525682-301ddc00-2ca5-11e9-85d1-d1f971e86fc5.png)
I have mysql-python==1.2.4b4 in my requrements.txt file, and in my pip list.
I'm using python 2.7.13 and I've created the Procfiles.
For some reason I keep getting this error, I don't know if it's anything to do with the SSL certificate, if so do you know how I can fix it. My github is https://github.com/Jonnoramo/Jonathans_Music_Store.
Thanks very much for your help.

**Comment by chrismattmann** [comment]
hi @Jonnoramo this isn't a Tika Python issue. Seems like there is an issue with your Python installation not supporting SSL.
