### ISSUE TITLE
Need to check port is open in parser/detector/config

### ISSUE THREAD

**Issue by dongnizh** [chrismattmann/tika-python#23]
Hi, @chrismattmann it seems that we need to add port checking in these functions. Because I just check port in runCommand function, but no in these functions.

Any suggestions on this?

**Comment by dongnizh** [comment]
This one is related to #24.

**Comment by chrismattmann** [comment]
Hey @dongnizh in these functions they are calling runCommand at some level, right? Or not?

**Comment by dongnizh** [comment]
No, they are not calling runCommand. runCommand is calling these by cmd option.

**Comment by chrismattmann** [comment]
I have an idea - why not just move your port checking code into callServer? runCommand at its bottom core calls callServer, so if you check in callServer it will satisfy all cases, right?

**Comment by chrismattmann** [comment]
@dongnizh

**Comment by dongnizh** [comment]
@chrismattmann Yes, will do.

**Comment by chrismattmann** [comment]
Solved in #26 and in #27
