### ISSUE TITLE
Not working behind proxy

### ISSUE THREAD

**Issue by green999** [chrismattmann/tika-python#233]
The parser is not working with Docker inside the proxy. Returns 502 (timed out). 

I did set the os.Environ for the JAR url (inside my code before importing tika)
I did setup the ENV variables for HTTP_PROXY/HTTPS_PROXY. 
Also, I have the same at the docker config file.

I am not sure how to set the config to use the local JAR file (instead of downloading), which I have it part of my Docker image.

Any thoughts?

Thanks!

**Comment by chrismattmann** [comment]
If you just download a local Tika server jar, i your docker, then start up the tika server on localhost:9998 (default port), it will use that by default and not start Tika server on its own. Good luck!
