### ISSUE TITLE
Tika server returned status: 422

### ISSUE THREAD

**Issue by MiaHuang97** [chrismattmann/tika-python#234]
I tried running the following code:
import tika
from tika import parser
parsed = parser.from_file('/path/to/file', xmlContent=True)
print(parsed["metadata"])
print(parsed["content"])

the tika log returned:
2019-07-05 14:47:22,087 [MainThread  ] [WARNI]  Tika server returned status: 422

**Comment by sfai05** [comment]
Same issue here. I checked Tika server at http://localhost:9998/ and it seems fine to me

**Comment by chrismattmann** [comment]
need more status and haven't seen anything on this since July. This happens periodically if it's unable to parse the file directly - try tika-app and see if it is able to parse it.
