### ISSUE TITLE
ok with 1.22 but 404 error response with 1.8 versions of tika server jar daemon

### ISSUE THREAD

**Issue by uklg** [chrismattmann/tika-python#242]
#!/usr/bin/python3
parsed = parser.from_file(fname, "http://%s:9998/tika" % host)

with 1.8 version of tika server jar:
2019-10-04 16:40:02,393 [MainThread  ] [WARNI]  Tika server returned status: 404
{'status': 404}

but no errors with 1.22 version of tika server jar.

both using tika 1.19 pip3 module
 
not working:
Manifest-Version: 1.0
Implementation-Vendor: The Apache Software Foundation
Implementation-Title: Apache Tika server
Implementation-Version: 1.8
Implementation-Vendor-Id: org.apache.tika
Specification-Vendor: The Apache Software Foundation
Build-Jdk: 1.7.0_75
Built-By: tyler
Specification-Title: Apache Tika server
Created-By: Apache Maven
Specification-Version: 1.8
Main-Class: org.apache.tika.server.TikaServerCli
Archiver-Version: Plexus Archiver

working:

Manifest-Version: 1.0
Implementation-Title: Apache Tika server
Automatic-Module-Name: org.apache.tika.server
Implementation-Version: 1.22
Archiver-Version: Plexus Archiver
Built-By: timwork
Specification-Vendor: The Apache Software Foundation
Specification-Title: Apache Tika server
Implementation-Vendor-Id: org.apache.tika
Implementation-Vendor: The Apache Software Foundation
Main-Class: org.apache.tika.server.TikaServerCli
Created-By: Apache Maven 3.5.3
Build-Jdk: 1.8.0_172
Specification-Version: 1.22

not working curl path on 1.8

curl -I localhost:9998/rmeta/text
HTTP/1.1 404 Not Found
Allow: POST,GET,PUT,OPTIONS,HEAD
Content-Length: 0
Date: Fri, 04 Oct 2019 16:20:20 GMT
Server: Jetty(8.y.z-SNAPSHOT)

working curl path on 1.22:

curl -I localhost:9998/rmeta/text
HTTP/1.1 405 Method Not Allowed
Date: Fri, 04 Oct 2019 16:22:41 GMT
Allow: POST,GET,PUT,OPTIONS,HEAD
Content-Length: 0
Server: Jetty(9.4.z-SNAPSHOT)

**Comment by chrismattmann** [comment]
yep it only binds correctly to the API of the newer server with newer versions of the library if you want it to work with 1.8 tika download an old release.

**Comment by LaniakeaS** [comment]
same error, using tika2.6.0  in 20.04.1-Ubuntu docker container
