### ISSUE TITLE
get text position from from_file()

### ISSUE THREAD

**Issue by darioblabla** [chrismattmann/tika-python#243]
Hi, is there a way to get something like the following:

top="71" left="213" width="187" height="11" font="3" BOSQUE DE CIDROS 173 PISO 3

instead of just 

BOSQUE DE CIDROS 173 PISO 3

from 

parser.from_file(filename_pdf)  ??

Thanks

**Comment by jasonachonu** [comment]
Same here. i'm urgently need this. @darioblabla Please share if you find a solution to it

**Comment by chrismattmann** [comment]
call `parser.from_file('/path/to/file.pdf', xmlContent=True) and good luck!
