### ISSUE TITLE
How to get the images extracted by tika using the python wrapper ?

### ISSUE THREAD

**Issue by ChristelleG** [chrismattmann/tika-python#244]
Hello there,

Using tika jar on the command line interface, we can specify a path where tika will save the extracted images. 
Can we have the same behaviour with the python wrapper ? I see that it return some paths in the resulting dict (ex: X-TIKA:embedded_resource_path:'/thumbnail.jpeg' ) and images size parameters but where does the images are saved by default ? I suppose in a tmp folder?

**Comment by chrismattmann** [comment]
yes  @ChristelleG it saves it in the tmp dir where Tika is deployed I suppose. Right now there is no API call in tika-python to specify this like in the Java API. if you have the inclination PRs to add it to the Python library would be welcomed.
