### ISSUE TITLE
Build errors.

### ISSUE THREAD

**Issue by ipsmile** [chrismattmann/tika-python#247]
Downloaded the source code about two hours ago and try to build using mvn install. Received the following errors while building the Tika-core. 

[INFO] --- clirr-maven-plugin:2.8:check (default) @ tika-core ---
[ERROR] Unable to locate enclosing class org.apache.tika.language.LanguageProfile for nested class org.apache.tika.language.LanguageProfile$1
[ERROR] Unable to locate enclosing class org.apache.tika.language.LanguageProfile for nested class org.apache.tika.language.LanguageProfile$Counter
[ERROR] Unable to locate enclosing class org.apache.tika.language.LanguageProfile for nested class org.apache.tika.language.LanguageProfile$Interleaved
[ERROR] Unable to locate enclosing class org.apache.tika.language.LanguageProfilerBuilder for nested class org.apache.tika.language.LanguageProfilerBuilder$NGramEntry
[ERROR] Unable to locate enclosing class org.apache.tika.language.LanguageProfilerBuilder for nested class org.apache.tika.language.LanguageProfilerBuilder$QuickStringBuffer
[INFO] Succeeded with 0 errors; 0 warnings; and 0 other changes.

Just like to raise the flag and hopefully some one will look into it.

Thanks a great deal.

Ip

**Comment by chrismattmann** [comment]
please take this to the `dev@tika.apache.org` mailing list. Thanks!
