### ISSUE TITLE
bug in latest version 1.22

### ISSUE THREAD

**Issue by yishairasowsky** [chrismattmann/tika-python#250]
File "C:\Users\Yishai\AppData\Local\Programs\Python\Python37\lib\site-packages\tika\tika.py", line 549, in callServer
    encodedData.close() # closes the file reading data

**Comment by jimmychordia** [comment]
I am also getting the same error -   AttributeError: 'bytes' object has no attribute 'close'. Does anyone has the fix to this. Please post.

**Comment by luke4u** [comment]
try to comment out this line. it worked for me.

**Comment by chrismattmann** [comment]
fixed in https://github.com/chrismattmann/tika-python/pull/253
