### ISSUE TITLE
Program suddenly stopped extracting

### ISSUE THREAD

**Issue by cerava** [chrismattmann/tika-python#254]
I'm running tika version 1.19 to extract text from a PDF and it's been working fine - however it recently stopped working despite me not making any changes on my system (did not upgrade to 1.22, did not upgrade tika, did not upgrade Java)

The particular line in question is:
`content = parser.from_file(current_file)['content']`

Previously the above line would be able to extract all the content, but now it's merely returning
`
retrievePDF.jsp

`

with a lot of whitespace ahead and behind it. Is `retrievePDF.jsp` the name of the file/process tika runs to retrieve PDF files? Is tika not running properly on my system and thus the "extracted" PDF is merely the name of the JSP that's supposed to do the retrieving?

Does anyone have any idea what went wrong and how I'd be able to get it running again? Thanks!

**Comment by chrismattmann** [comment]
maybe try killing your tika server (ps aux | grep java | grep tika) and then kill it and then restart?
