### ISSUE TITLE
whether have file size limitation for parsing the file content?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#257]
@chrismattmann 
    i prepare to parse the mongo gridfs file and take it as a flask api service and expose it to outer caller, whether have file size limitation for parse the file content using tika-python? thanks

**Comment by chrismattmann** [comment]
hi @sunweiconfidence I believe the answer is no....but best to check on by sending an email to [dev@tika.apache.org](mailto:dev@tika.apache.org) and check.

**Comment by sunweiconfidence** [comment]
@chrismattmann  thanks for your answer, and i have send email to your supplied email and wait for reply
