### ISSUE TITLE
how to speed up extract file's time for the first time?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#260]
@chrismattmann 
    if my flask web api don't be called for some hours, and again call the tika's from_buffer method, it will become very slow, then wait for several seconds,the second time i call this method, it will become faster than first time, do i have any setting code for solve the cold start issue? thanks

**Comment by chrismattmann** [comment]
looks like this is related to your other issue, so I assume is fixed now.
