### ISSUE TITLE
ResourceWarning when executing tests

### ISSUE THREAD

**Issue by jjelosua** [chrismattmann/tika-python#262]
~/code/tika-python/tika/tika.py:579: ResourceWarning: unclosed <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 51870), raddr=('127.0.0.1', 9998)>
  alreadyRunning = checkPortIsOpen(serverHost, port)
ResourceWarning: Enable tracemalloc to get the object allocation traceback

The statement to close the socket use to test if tika is up https://github.com/chrismattmann/tika-python/blob/master/tika/tika.py#L764 is unreacheable.

**Comment by chrismattmann** [comment]
thanks @jjelosua i'll merge this and #263 via #264
