### ISSUE TITLE
ResourceWarning when executing tests

### ISSUE THREAD

**Issue by jjelosua** [chrismattmann/tika-python#263]
~/code/tika-python/tika/tika.py:329: ResourceWarning: unclosed file <_io.BufferedReader name='/var/folders/1l/bn7nfys51f98tfxk1y7_5q700000gq/T/boe-dias-2019-12-02-pdfs-boe-a-2019-17288.pdf'>
  headers, verbose, tikaServerJar, config_path=config_path, rawResponse=rawResponse, requestOptions=requestOptions)

The parent caller to `CallServer` should be responsible for the closure of the file/objects

**Comment by chrismattmann** [comment]
thanks @jjelosua
