### ISSUE TITLE
Have `.from_file()` methods accept file objects as input

### ISSUE THREAD

**Issue by edwin-lai** [chrismattmann/tika-python#267]
Currently the `.from_file()` methods only accept urls and filepaths as input. I would like it to accept file objects as well so applications that have already opened the files don't have to write the file again for Tika to consume. I am willing submit a pull request that implements this feature.

**Comment by chrismattmann** [comment]
thanks @edwin-lai i'll watch for the PR!

**Comment by nupanick** [comment]
@edwin-lai Can you please make sure that when you accept an open file stream from an outside source, you leave the stream open? Tika's auto-close behavior is unexpected.

**Comment by deepakjindal90** [comment]
Hey,

Is this implemented already, i have file as byte code and i want to extract content from that without writing that byte content to a file, can we achieve that in pyhton?

Thanks
Deepak Jindal
deepakjindaldj2007@gail.com
7838068727

**Comment by chrismattmann** [comment]
not to my knowledge, no @deepakjindal90

**Comment by chrismattmann** [comment]
fixed in #316
