### ISSUE TITLE
How do i change the JVM size to greater than 4Gb RAM When tika parse the file?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#271]
@chrismattmann
if i want to increase the JVM size to greater than 4Gb RAM for high concurrency need, how do i change the code to implement it? thanks

**Comment by chrismattmann** [comment]
@sunweiconfidence look at tika/tika.py and search for the startServer function. You can change it there.

**Comment by sunweiconfidence** [comment]
@chrismattmann  thanks for your answer
