### ISSUE TITLE
how to solve the 422 error code issue for parsing the doc file that containing many pictures?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#272]
hi @chrismattmann 

when i parse a doc file of 150MB, include 140MB pictures in it, every time i parse the file, i meet with 422 error status code using parser.from_buffer method, even if i set the TikaJavaArgs = os.getenv("TIKA_JAVA_ARGS", '-Xmx32g -Xmn20g') in tika.py to increase the JVM performance, still meet with 422 error statuscode, how can i fix the issue? thanks

**Comment by sunweiconfidence** [comment]
@chrismattmann 
have solved by read tika-server.jar sourcecode exception part, i found that when i save the doc file to docx format, file can be parsed easily

**Comment by chrismattmann** [comment]
thanks for this @sunweiconfidence !
