### ISSUE TITLE
`module 'tika' has no attribute 'initVM'` and `ImportError: cannot import name 'parser'`

### ISSUE THREAD

**Issue by agiokas-dbg** [chrismattmann/tika-python#277]
I've followed the installation instructions, using pip in a virtual environment:
- `python3 -m venv venv`
- `source venv/bin/activate`
- `pip install tika`
- `wget -O /tmp/tika-server.jar http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.23/tika-server-1.23.jar`
- `wget -O /tmp/tika-server.jar.md5 http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.23/tika-server-1.23.jar.md5`

And then setup the environment variables:

```
TIKA_VERSION=1.23
TIKA_CLIENT_ONLY=True
TIKA_PATH=/tmp/tika-server.jar
TIKA_JAVA=java
PYTHONIOENCODING=utf8
```

I've also tried to add the jar in the current working directory and use this instead:

```
TIKA_VERSION=1.23
TIKA_JAVA=java
TIKA_SERVER_JAR="file:////tika-server.jar"
PYTHONIOENCODING=utf8
```

When using the example script:

```
import argparse
import tika
tika.initVM()
from tika import parser

ap = argparse.ArgumentParser(prog='extractor',
                        description='Extract Text from PDF programmatically')
ap.add_argument("--input", required = True, help = "Path to the PDF file.")
args = vars(ap.parse_args())
print("WARNING: export PYTHONIOENCODING=utf8")

parsed = parser.from_file(args['input'])
print(parsed["content"])
```
I get `module 'tika' has no attribute 'initVM'` and when I remove the `tika.initVM()` I get `ImportError: cannot import name 'parser'`.

**Comment by mathiashoeld** [comment]
are you getting the same issue with older versions, e.g. `TIKA_VERSION=1.22`?

**Comment by agiokas-dbg** [comment]
Hi @mathiashoeld I just tried it with version 1.22 and I am getting the same issue. Should I try with an even older version? What annoys me is that my colleague is running it in docker with 1.23 using the same code, and it works fine.

**Comment by chrismattmann** [comment]
If you are in a local checkout of tika-python when running it, you will get module import errors. Try cd'ing out of the Git checkout (if you are running this from that dir) and see if that fixes it @agiokas-dbg

**Comment by aabid0193** [comment]
Was this issue ever resolved? I am still having this issue if installing with pip

**Comment by agiokas-dbg** [comment]
I never managed to solve this.

**Comment by chrismattmann** [comment]
@aabid0193 @agiokas-dbg can you find your $PYTHON site-packages directory and then rm -rf tika* out of there? Try it on a fully fresh Python install. the .initVM() is likely related to the parser module not found. For whatever reason your tika library isn't being loaded or installed correctly.

FWIW, .initVM is no longer needed and only  left in for back compat.
