### ISSUE TITLE
Fixed port leads to problems on Windows 10

### ISSUE THREAD

**Issue by BorisWiegand** [chrismattmann/tika-python#286]
On version 1.23.1, the port of the tika server is set to "9998" in line 175 of tika.py. 
However, this port is already in use by a system process on my Windows 10 system. It would be nice, if there would be an option in the library to change this port. 
Might be related to the closed issue https://github.com/chrismattmann/tika-python/issues/206

**Comment by chrismattmann** [comment]
Hi @BorisWiegand see the documentation in https://github.com/chrismattmann/tika-python/blob/master/tika/parser.py#L23 you can provide your own custom Tika Server end point which should take care of it.
