### ISSUE TITLE
How many languages does Tesseract OCR of Tika-Python support for parsing in pictures?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#290]
hi @chrismattmann,

i want to use Tesseract OCR in tika-python, i have three questions as below:

How many languages does Tesseract OCR support for parsing in pictures? like French,German,Chinese and so on
Do i need to pass language parameters when parsing pictures?
Whether to support parsing multiple languages in a picture at the same time?

thank you

**Comment by chrismattmann** [comment]
Please check the [full documentation on OCR and Tika Server](https://cwiki.apache.org/confluence/display/TIKA/TikaOCR) which I think will help answer your question @sunweiconfidence

**Comment by sunweiconfidence** [comment]
thanks @chrismattmann
