### ISSUE TITLE
How many languages tika-python supports to parse attachments?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#291]
hi @chrismattmann 

i have a question that How many languages tika-python supports to parse attachments? because i haven't tested all languages for parsing file that contain many languages' content before, thanks.

**Comment by chrismattmann** [comment]
it supports full unicode/UTF-8 and can extract text in multiple languages see [this tutorial](https://www.wisdomjobs.com/e-university/apache-tika-tutorial-1976/tika-language-detection-23409.html) though it's specific to Java, note it's exposed by Tika Server, and Tika Python just inherits it.

**Comment by sunweiconfidence** [comment]
thanks @chrismattmann
