### ISSUE TITLE
Which method should I call to parse the content of image when tesseract-ocr is turned on?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#292]
hi @chrismattmann 

i want to use tesseract-ocr to parse image's content, if tesseract-ocr has installed in my local pc and have path, which method should i call to parse the image's content using tesseract-ocr? thanks.

**Comment by chrismattmann** [comment]
thanks @sunweiconfidence if it's install it should automatically pick up Tesseract and call it.

**Comment by sunweiconfidence** [comment]
thanks @chrismattmann , but have a question that if the image's content is not english, it is German text and french text, tesseract need to pass language parameter, if i don't call method, how do you know what language parameter should pass to you? how do you automatically recognize it? thanks

**Comment by chrismattmann** [comment]
suggestion here is to create a wrapper around /usr/local/bin/tesseract (or wherever it is in your path), and then simply make that wrapper script pass the language parameters and then $* after, so that the binary will get called by tika with the right parameters. @sunweiconfidence

**Comment by sunweiconfidence** [comment]
hi @chrismattmann ,
could you provide an example for it? i am not clearly how to do it? thanks

**Comment by chrismattmann** [comment]
yes, find out where your `tesseract` is:

on Linux:
`which tesseract`

If that path is e.g., `/usr/local/bin/tesseract` then do the following:
  1. `mv /usr/local/bin/tesseract /usr/local/bin/tesseract.run`
  2. `vi /usr/local/bin/tesseract`

Then add the following to that file:
```bash
#!/bin/bash

/usr/local/bin/tesseract.run <parameters> $*

```

Set <parameters> to the options you want. Then to call your "tesseract" wrapper you call /usr/local/bin/tesseract as you would before, but this time it h as your flags turned on by default. Make sure to `chmod +x /usr/local/bin/tesseract`. HTH! @sunweiconfidence

**Comment by sunweiconfidence** [comment]
@chrismattmann  thanks for your detail information.
