### ISSUE TITLE
how do you know what language parameter should pass to you when use tesseract?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#294]
hi @chrismattmann 

i have a question that if the image's content is not english text, it is German text and french text, tesseract need to pass language parameter in its official document introduction, if i don't call method in tika-python for tesseract, how do you know what language parameter should pass to you? how do you automatically recognize it? thanks

**Comment by chrismattmann** [comment]
see my answer in #292
