### ISSUE TITLE
how can i deploy the tika-python to docker environment, have Dockerfile of tika-python?

### ISSUE THREAD

**Issue by sunweiconfidence** [chrismattmann/tika-python#297]
hi @chrismattmann 

i want to know whether have existing docker file to deploy the tika-python to docker environment? i found a tika-python docker file in docker hub
https://hub.docker.com/layers/thomasht86/tika-python-docker/latest/images/sha256-d3e2d51436d3db1b760568b7e078b9a14707586a909901da270535b05e9c9d54?context=explore

whether i can use above docker file of tika-python? thanks

**Comment by chrismattmann** [comment]
I don't publish an official Docker yet for tika-python, @sunweiconfidence but I will consider working on it. In the meanwhile, yes that referenced Docker looks good to me... 👍

**Comment by sunweiconfidence** [comment]
hi @chrismattmann  i will use the referenced docker file to try first, but i look forward to your docker file, thanks
