### ISSUE TITLE
Parser.from_file throws read timeout error with large word document

### ISSUE THREAD

**Issue by Sarthak049** [chrismattmann/tika-python#298]
Trying to parse a word document in python2.7 (I know that it is being depreciated, but few other dependencies work only in python2). But for few of the larger documents I am unable to get the parsed data. I am using the below code snippet to parse the document.

`headers = {
                "X-Tika-OCRLanguage": "eng",
                'timeout': 300,
                'pool_timeout':  300,
                "X-Tika-OCRTimeout": 300
            }
text_tika = parser.from_file(doc, xmlContent=False, requestOptions={'headers':headers})`

This code snippet throws following error:

`ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='localhost', port=9998): Read timed out. (read timeout=**60**)",),)`

Tried various request options to increase the read timeout but failed. Cannot find a way to tweak this setting, can you please help?
Great work with the library it helped me a lot!

**Comment by Sarthak049** [comment]
When I try the to make a curl request directly the response time is somewhere around 50sec. * Connection #0 to host localhost left intact 49.856982s

**Comment by chrismattmann** [comment]
are you doing this?

```
from tika import parser
parsed = parser.from_file('/path/to/file', requestOptions={'timeout': 120})
```

timeout is the only  one that matters to the requests library...which is where it looks like the timeout is occurring.

@Sarthak049

**Comment by Sarthak049** [comment]
Thank you for you time and response @chrismattmann. That was indeed the problem, I was passing the timeout parameter inside the headers key. My bad the solution was staring right at my face. Thanks again man. Amazing work!

**Comment by chrismattmann** [comment]
thank you @Sarthak049 !
