### ISSUE TITLE
Unable to read scanned content from PDF from tika-python

### ISSUE THREAD

**Issue by ssparasuram** [chrismattmann/tika-python#299]
Here i have tried to read the pdf contents which were scanned.

import tika
tika.initVM()

from tika import parser

PDF_file = "Sample.pdf"

with open(PDF_file, 'rb') as file_obj:
    parsed = parser.from_file(file_obj)

Empty result is coming.

if I convert this pdf pages into individual images and then parse, I can able to read the content.

Kindly help to parse the content of scanned document with out creating interim images.

Thanks.

**Comment by chrismattmann** [comment]
hi @ssparasuram instead of a file object, use a file path to the `.from_file` method. Should work fine.

**Comment by ssparasuram** [comment]
Dear @chrismattmann ,

As per your suggestion I have tried to read the content as .from_file by passing the file name.

Since that pdf has scanned document, i cannot read the text from below python coe:

def extract_text_from_attachment_base(PDF_file):
    parsed = parser.from_file(PDF_file)
    contenttype= parsed["metadata"]['Content-Type']
    try:
        if(contenttype.lower().__contains__("image")):
            return ""
        parsedcontent = parsed["content"]
        print(parsedcontent)
    except:
        print("unable to parse the attachment")

pdf_file_name = "SampleTableScanned.pdf"   

extract_text_from_attachment_base(pdf_file_name)

The same can help to read normal pdf files.

[SampleTableScanned.pdf](https://github.com/chrismattmann/tika-python/files/4454282/SampleTableScanned.pdf)
[SampleTable.pdf](https://github.com/chrismattmann/tika-python/files/4454283/SampleTable.pdf)


Kindly help.

**Comment by ssparasuram** [comment]
{'metadata': {'Author': 'Parasuraman Sakkarapani', 'Content-Type': 'application/pdf', 'Creation-Date': '2020-04-09T05:51:52Z', 'Last-Modified': '2020-04-09T05:51:52Z', 'Last-Save-Date': '2020-04-09T05:51:52Z', 'X-Parsed-By': ['org.apache.tika.parser.DefaultParser', 'org.apache.tika.parser.pdf.PDFParser'], 'X-TIKA:embedded_depth': '0', 'X-TIKA:parse_time_millis': '129', 'access_permission:assemble_document': 'true', 'access_permission:can_modify': 'true', 'access_permission:can_print': 'true', 'access_permission:can_print_degraded': 'true', 'access_permission:extract_content': 'true', 'access_permission:extract_for_accessibility': 'true', 'access_permission:fill_in_form': 'true', 'access_permission:modify_annotations': 'true', 'created': '2020-04-09T05:51:52Z', 'creator': 'Parasuraman Sakkarapani', 'date': '2020-04-09T05:51:52Z', 'dc:creator': 'Parasuraman Sakkarapani', 'dc:format': 'application/pdf; version=1.5', 'dc:language': 'en-GB', 'dcterms:created': '2020-04-09T05:51:52Z', 'dcterms:modified': '2020-04-09T05:51:52Z', 'language': 'en-GB', 'meta:author': 'Parasuraman Sakkarapani', 'meta:creation-date': '2020-04-09T05:51:52Z', 'meta:save-date': '2020-04-09T05:51:52Z', 'modified': '2020-04-09T05:51:52Z', 'pdf:PDFVersion': '1.5', 'pdf:charsPerPage': '1', 'pdf:docinfo:created': '2020-04-09T05:51:52Z', 'pdf:docinfo:creator': 'Parasuraman Sakkarapani', 'pdf:docinfo:creator_tool': 'Microsoft® Word 2013', 'pdf:docinfo:modified': '2020-04-09T05:51:52Z', 'pdf:docinfo:producer': 'Microsoft® Word 2013', 'pdf:encrypted': 'false', 'pdf:hasMarkedContent': 'true', 'pdf:hasXFA': 'false', 'pdf:hasXMP': 'false', 'pdf:unmappedUnicodeCharsPerPage': '0', 'producer': 'Microsoft® Word 2013', 'resourceName': "b'SampleTableScanned.pdf'", 'xmp:CreatorTool': 'Microsoft® Word 2013', 'xmpTPg:NPages': '1'}, 'content': None, 'status': 200}

**Comment by ssparasuram** [comment]
Kindly help

**Comment by chrismattmann** [comment]
what is the size of your PDF file? check the logs for your tika server in `/tmp/tika-server*.log*` check if it is running out of memory... @ssparasuram
