### ISSUE TITLE
API to shutdown tika server

### ISSUE THREAD

**Issue by robguinness** [chrismattmann/tika-python#301]
Is there any API to shutdown the tika server after it is no longer needed? It would be nice to be able to do this programmatically from within a python script (after the tika server is no longer needed).

**Comment by igponce** [comment]
At first sight, to implement that feature we would need:

- A way to record the java process_id (multi platform) on start.
- A (temporary) place to store that process Id 
- A way to kill the process (multiplatform)

Out of scope:
Killing tija process after program ends.

**Comment by fipwmaqzufheoxq92ebc** [comment]
`from tika import tika`
`tika.killServer()`
https://github.com/chrismattmann/tika-python/blob/178a33b9338cfb0f29f3c12062e92bd26221c9e4/tika/tika.py#L699
It was added in 1.23.1 and updated in 1.24

**Comment by chrismattmann** [comment]
correct @fipwmaqzufheoxq92ebc this was added in 1.24.
