### ISSUE TITLE
[MainThread  ] [WARNI]  Tika server returned status: 500

### ISSUE THREAD

**Issue by suresh-vy** [chrismattmann/tika-python#302]
Hi 

While working with 1.7GB zip file i'm getting below error 

[MainThread  ] [WARNI]  Tika server returned status: 500

currently i'm using tika-python version 1.2.4

in my environmental variable I set java_OPTS

JAVA_OPTS=-Xms2024m -Xmx4096m -Xss2024m -Xmn512m

Could please tell me how to work with large file using tika-python

**Comment by chrismattmann** [comment]
hi @suresh-vy can you try starting a tika server on your own (before running tika python) with your desired requirements for memory? Then try tika-python and see if it works? My guess is that  your opts weren't being propagated to the server.
