### ISSUE TITLE
Unable to pare the PDF content which is not in vertical orientation

### ISSUE THREAD

**Issue by ssparasuram** [chrismattmann/tika-python#303]
Dear Members,

I am currently using Tika-Python.

def tika_parser(file_path):
    # Extract text from document
    content = parser.from_file(file_path)
    if 'content' in content:
        text = content['content']
    else:
        return " [*IMAGE] "
    # Convert to string
    text = str(text)
    return text

when i am trying to read the content from the pdf which is not vertical orientation in all the pages, not parsing the content correctly.

Kindly help

**Comment by chrismattmann** [comment]
hi @ssparasuram please check upstream in the Tika java library, for configuration options. Are you using Tesseract, or if you are using just the default PDF parser, i think you need to change the properties upstream. Contact [user@tika.apache.org](mailto:user@tika.apache.org) for guidance.
