### ISSUE TITLE
double list embedded

### ISSUE THREAD

**Issue by dongnizh** [chrismattmann/tika-python#31]
Hi, @chrismattmann look at this:

![7edcc94a-9bfc-452d-8c53-bb68582761b6](https://cloud.githubusercontent.com/assets/6832510/7484675/41aeab4a-f340-11e4-8093-149fbe71c1bf.png)

After parsing by parser in tika-python, this one shows:

![fb7a1240-90b3-490a-934d-3b5aad896284](https://cloud.githubusercontent.com/assets/6832510/7484726/c1b8a1e2-f340-11e4-880d-05f32db325e6.png)

with double list symbol on it. 
Can we just keep one list symbol and release the other one in order to keep it the same with other metadata values？Or you want to use it for some other reasons?

**Comment by chrismattmann** [comment]
let's baseline off the way that tika-python is currently doing it @dongnizh - that's the baseline going forward.
