### ISSUE TITLE
Tika Parser raises json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by stubclan** [chrismattmann/tika-python#312]
Steps to reproduce:
Below code runs perfect in Windows system but generates JSONDecodeError in Debian
```
from tika import parser

with open('./test.txt', 'r') as fh:
    file_content = fh.read()
    parsed = parser.from_buffer(file_content)
```

![image](https://user-images.githubusercontent.com/6322130/84323683-dbaa9b00-ab3c-11ea-81b3-d110a32be2a6.png)

**Comment by chrismattmann** [comment]
looks like your Tika server didn't start. Please  make sure it's running or look at the log message in /tmp/tika*.log
