### ISSUE TITLE
Duplicate characters returned when extracting text from PDF

### ISSUE THREAD

**Issue by JSB97** [chrismattmann/tika-python#314]
When I extract the text from a PDF,  tika-python returns duplicated letters for some words, which i want to avoid.

In the java version of tika, The issue seems to be resolved by assigning "suppressDuplicateOverlappingText" to be true  (link below), but how can I achieve this in the python implementation?

https://issues.apache.org/jira/browse/TIKA-960

**Comment by bpluly** [comment]
Using it in the parse call as a request option?
Something like 
>parser.from_file('/path/to/file', requestOptions={'suppressDuplicateOverlappingText': True})

**Comment by chrismattmann** [comment]
suggested help from @bpluly looks good to me. 👍
