### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by Tushar-Mehndiratta** [chrismattmann/tika-python#319]
I am facing an error while trying to convert a .docx file to xhtml output.
Similar issue was faced in several other (doc/docx/pdf files)

UnicodeEncodeError Description:
![image](https://user-images.githubusercontent.com/62862528/88059440-79ed4000-cb82-11ea-98b0-fbbc35f41ae8.png)

Program Code that I used:
![image](https://user-images.githubusercontent.com/62862528/88059533-9d17ef80-cb82-11ea-9461-9d585a731b9a.png)
`from tika import parser

file_name = input("Enter the file name :")

def extract_html_text(file_name):
    parsed_html = parser.from_file(file_name, xmlContent=True)
    parsed_html_text = parsed_html['content']
    return parsed_html_text

html_text = extract_html_text(file_name)

print(html_text)
`

Also, Can I get help with this: 
![image](https://user-images.githubusercontent.com/62862528/88059679-d05a7e80-cb82-11ea-8335-761bee755986.png)

**Comment by chrismattmann** [comment]
looks like your Python code that calls Tika is taking in an input file name that includes unicode. You may want to change your code to to:

`file_name = codecs.decode(input('Enter the file name:'), "utf-8")`

**Comment by Tushar-Mehndiratta** [comment]
It raises another error:
![image](https://user-images.githubusercontent.com/62862528/89094454-b1a98280-d3e1-11ea-90b0-cee887403ada.png)

**Comment by chrismattmann** [comment]
See [this article](https://docs.python.org/3/howto/unicode.html). You have to read the filename string in UTF-8. I didn't literally mean take the code I gave and paste it, sorry it was pseudo code and I didn't try to run it. Good luck!

**Comment by Tushar-Mehndiratta** [comment]
Ok, I found another similar way to do that without using codecs module.

Also, Can I get help with this:
![image](https://user-images.githubusercontent.com/62862528/89113286-816aee00-d48c-11ea-97fb-eb5270bcc13d.png)

This occurs first time(on each new day) I run the code. Due to this there is a delay in getting the output

**Comment by chrismattmann** [comment]
Thanks @Tushar-Mehndiratta I don't have a fix for the failed to see the startup log message, however you can safely ignore it, as Tika still works fine even if it doesn't see the log output on first run.

**Comment by Tushar-Mehndiratta** [comment]
But it causes a huge delay (15 seconds- 50 seconds) in executing the whole code

**Comment by chrismattmann** [comment]
I suppose we could consider putting in an option to not check but overall you need to check for the log to  be written in order  to run the client (aka the server needs to be running after starting). It's never 15 seconds. It's a few seconds. If you have  a better idea and/or sample PR  that illustrates it I'm all ears.

**Comment by Tushar-Mehndiratta** [comment]
Maybe we could put a time bound, that if the log file is not found within (say) 5 seconds, if not then it could make a new log file... What do you think about this ?

**Comment by chrismattmann** [comment]
well the danger is not to get the log file to be created via Python - the thing that creates the log file is the starting of the Tika server ... so if that log file isn't created you want it to error out.
