### ISSUE TITLE
Incorrectly Parsing Fraction

### ISSUE THREAD

**Issue by dguis** [chrismattmann/tika-python#321]
Hello! I was attempting to parse a PDF with tika, but when I tried to parse a fraction it would return a format I was not able to use. For example, 10/30 would result in 3010, an I have no way of determining what the original value was meant to be. Is there any way I can get around this? Thanks!

**Comment by chrismattmann** [comment]
Check out the PDFParser options in the upstream Tika java library. You can also send a note to [dev@tika.apache.org](mailto:dev@tika.apache.org) with any further questions.
