### ISSUE TITLE
Incorrect formatted text for PDF's

### ISSUE THREAD

**Issue by Tushar-Mehndiratta** [chrismattmann/tika-python#323]
The following code was used to extract the pdf text and output later being stored into an html file

```
import tika
from tika import parser
parsed = parser.from_file('/path/to/file', xmlContent=True)
print(parsed["content"])
```

The problem i am facing is that although all the text is extracted successfully, but it is not able to retain the text styling(bold, italic, underline font size, etc.). The problem is faced only in PDF's; for word files(docx, doc) it works great.

**Comment by chrismattmann** [comment]
please check the upstream Tika java library and the PDF parser. There are a number of options to set there. Any further questions send them to [dev@tika.apache.org](mailto:dev@tika.apache.org)
