### ISSUE TITLE
Formatted Text Printing

### ISSUE THREAD

**Issue by Zast996** [chrismattmann/tika-python#324]
Hello,
in the java version of Tika, in particular in the tika GUI app, there is the possibility to print the raw text (after the conversion from PDF, docx etc..) in several formats, like "Formatted text", "Plain Text", "Main Content", "Structured Text".
Is there the possibility to get this formats through tika python?
Many thanks in advance

**Comment by chrismattmann** [comment]
Please ask your question upstream at [dev@tika.apache.org](mailto:dev@tika.apache.org)
