### ISSUE TITLE
use -spawnChild mode

### ISSUE THREAD

**Issue by tballison** [chrismattmann/tika-python#325]
We added -spawnChild mode to tika-server to defend against catastrophic failures -- oom, infinite loops etc.  We should make this the default in tika-python.  We'll need to make the python client a bit more robust to handle those times when tika-server is restarting.

**Comment by chrismattmann** [comment]
@tballison agree can you provide a PR for merging into tika-next?

**Comment by chrismattmann** [comment]
please create a new PR/issue when you have the update ready. Also provide a test to expose this for regression. Thanks.
