### ISSUE TITLE
classpath functionality is broken on Windows 10

### ISSUE THREAD

**Issue by mirrord** [chrismattmann/tika-python#327]
The startServer function attempts to concatenate the given classpath to the tika jar path with a colon. This is appropriate for Linux, but not for Windows where the correct character is the semicolon.

the problem lies (in part) on line 639 of tika.py:
```
    if classpath:
        classpath += ":" + tikaServerJar
```
should instead be:
```
    if classpath:
        if Windows:
            classpath += ";" + tikaServerJar
        else:
            classpath += ":" + tikaServerJar
```

The second half of this issue is that including a naked semicolon causes CLI parsing errors, so the whole classpath variable must be wrapped in quotes.

**Comment by chrismattmann** [comment]
Fixed in https://github.com/chrismattmann/tika-python/commit/47aebcbe1c7d3f3a697d27fc64953f81eba0e4fa
