### ISSUE TITLE
resourceName returns byte character

### ISSUE THREAD

**Issue by ddriver3487** [chrismattmann/tika-python#333]
Not sure why but the filename, key 'resourceName',  is being returned as a string, but with the byte characters included. Is this intended?

![image](https://user-images.githubusercontent.com/16365835/107247925-cbb2c600-69ff-11eb-8ff0-8da25f5e6881.png)

**Comment by chrismattmann** [comment]
Yes likely to do with Unicode and your locale. Check your OS Locale and Unicode settings.

**Comment by ddriver3487** [comment]
Thanks for the reply. These are my locales. Anything here that would cause this?
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
