### ISSUE TITLE
LanguageDetectors

### ISSUE THREAD

**Issue by arky** [chrismattmann/tika-python#336]
@chrismattmann Am trying to test language detection of Apache Tika using your wonderful library. Am not sure the right way to listing the language detectors. 

https://tika.apache.org/1.25/api/org/apache/tika/language/detect/LanguageDetector.html#getLanguageDetectors--

And wondering if it possible to override the languages using similar process to https://github.com/chrismattmann/tika-python/wiki/Using-Tika-Translate

**Comment by chrismattmann** [comment]
Thank you @arky ! I haven't exposed ways to change the language detectors yet in the Tika Python client. Right now it just uses the default as they are set in the upstream Java tika library. I recommend making sure we have the flexibility there to achieve what you are looking for, and then we can propagate it down to the Python client here.
