### ISSUE TITLE
Using Tika with multithreading

### ISSUE THREAD

**Issue by AzureAlph** [chrismattmann/tika-python#337]
Hi, Im not sure how I would describe or ask this but, is there any incompatibility or limit when trying tika on a python script that uses multi threading for multiple files?

I noticed i get the "Failed to receive startup confirmation from startServer." error occasionally but trying it multiple times, it seems to occur on different files

**Comment by chrismattmann** [comment]
Yeah it shouldn't have any limitations other than the underlying OS, ulimit and threading capabilities of your computer. But the library itself is scalable and multi-threaded.
