### ISSUE TITLE
Git history has heavy binaries

### ISSUE THREAD

**Issue by ahmadia** [chrismattmann/tika-python#34]
This makes the repository unnecessarily fat.  I can trim out all the .jar files from the history if you don't mind :)

**Comment by chrismattmann** [comment]
what's the potential MB savings @ahmadia ? My only concern is destroying version history..but do you have an idea of the savings?

**Comment by ahmadia** [comment]
Probably about 98% of the weight?  This repository should only be a couple
mb. We can leave a note with the list of jar files removed from history.

**Comment by chrismattmann** [comment]
Go for it! Sounds good

**Comment by chrismattmann** [comment]
@ahmadia any progress here?

**Comment by ahmadia** [comment]
Yup, just created a branch.  Need to open a PR.

**Comment by ahmadia** [comment]
Actually, this can't be done as a PR since you don't want to merge history here, you need to replace it.

**Comment by ahmadia** [comment]
Take a look at this: https://github.com/ahmadia/tika-python/tree/ahmadia/strip-jars

Should preserve history except the .jar files are gone.

**Comment by ahmadia** [comment]
Can't be merged in, you'd need to just reset your master branch to that series of commits.  I'd keep a copy of the master branch for awhile just in case I knuckled it up.

**Comment by ahmadia** [comment]
repository shrinks from 50 MB to 228KB.

**Comment by chrismattmann** [comment]
Not exactly sure how to proceed here? How do I take advantage of your branch? @ahmadia

**Comment by ahmadia** [comment]
Give me commit rights to this repository and I'll take care of the rest :)

**Comment by chrismattmann** [comment]
No probs will do shortly @ahmadia

**Comment by chrismattmann** [comment]
Perms granted

**Comment by chrismattmann** [comment]
@ahmadia just FYI granted you perms

**Comment by ahmadia** [comment]
Cool.  I'll get to it tomorrow.

**Comment by ahmadia** [comment]
It's done.  You'll need to get the new master branch (and avoid merging any PRs from the old master).

**Comment by ahmadia** [comment]
I saved the branch to here: https://github.com/chrismattmann/tika-python/tree/backup-master
