### ISSUE TITLE
Bold text repeating twice

### ISSUE THREAD

**Issue by Shradha27** [chrismattmann/tika-python#346]
If **bold** formatting is achieved by writing a word twice in a document, `tika` is also repeating the words twice while parsing. Is there a way to handle this?

Code-
```
from tika import parser
parsed_data=parser.from_file(abc.pdf)
```

Example-
![image](https://user-images.githubusercontent.com/29987046/123826313-4895fc00-d91d-11eb-8018-bb7a163b6260.png)

Output-

`MGM Higher Secondary SchoolMGM Higher Secondary School MP Board // 2003 2005`

**Comment by chrismattmann** [comment]
Please check the upstream PDFBox and also Tika server library by mailing [dev@tika.apache.org](mailto:dev@tika.apache.org)
