### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ktoulgaridis** [chrismattmann/tika-python#349]
Since initVM is present just for compatibility reasons, I suppose the README could be updated to point this out.
It would also be nice to have an actual Tika Class which on init accepts the ENV_VARs as arguments, as it's impractical to work with them when remote workers are in place. (eg. Google Dataflow) That however is a discussion for another issue.

**Comment by chrismattmann** [comment]
Yeah I think I would be open to having a class with properties and so forth for Tika but it would require a bit of refactoring and is a separate issue. Thank you for your comment @ktoulgaridis If you get a chance to update the README go ahead and propose a PR and I'll take a look. Thanks.
