### ISSUE TITLE
Tika-Python doesn't work on windows

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-python#35]
I received the following email from Github user:

> I tried the Tika Lib for a project on Windows and saw that it doesn't permit to recognize a windows path.
> Perhaps, you only work on unices ;-)
> in 
```python
def getRemoteFile(urlOrPath, destPath):
    """Fetch URL to local path or just return absolute path."""
    #import pdb; pdb.set_trace()
    urlp = urlparse(urlOrPath)
    if urlp.scheme == '':
        return (os.path.abspath(urlOrPath), 'local')
    else:
        filename = urlOrPath.rsplit('/',1)[1]
        destPath = destPath + '/' +filename
        echo2('Retrieving %s to %s.' % (urlOrPath, destPath))
        urlretrieve(urlOrPath, destPath)
        return (destPath, 'remote')
```
> the urlp.scheme return the drive ( c or d, etc ...)
```python
>>> o=urlparse('c:\temp\toto.pdf')
>>> print o
ParseResult(scheme='c', netloc='', path='\temp\toto.pdf', params='', query='', fragment='')
```
> i corrected my installation of tika by changing into :
```python
if urlp.scheme not in ('http','https'):
    return(urlOrPath,'local')
and the 2nd line because 
>>> os.path.abspath('c:\temp\toto.pdf')
'C:\\Python27\\\temp\toto.pdf' wich is wrong
```
> best regards, 
> stéphane
> stephane.lambelin@laposte.net

**Comment by dongnizh** [comment]
@chrismattmann how about urlp.scheme in 'ftp' ?

**Comment by chrismattmann** [comment]
Can you investigate @dongnizh ? Thanks

**Comment by dongnizh** [comment]
@chrismattmann Emm...Try my best.......

**Comment by dongnizh** [comment]
@chrismattmann  the only way in my mind is writing a regular expression, since windows local file starts with **"\"**, while others starts with **"/"**. This will make them separated. Need  to find a way to test on Windows.

**Comment by dongnizh** [comment]
@chrismattmann the only way in my mind is writing a regular expression, since windows local file uses backslash,  while unix/linux use slash. We can make them separated. Not sure whether it is working or not. Need to test on Windows or think a better way instead.

**Comment by chrismattmann** [comment]
@dongnizh check this out http://stackoverflow.com/questions/11687478/convert-a-filename-to-a-file-url I think this may be a more general fix. I'm going to go ahead and commit #36 and then if we get something better with this URL, etc. we can open up a new issue.
