### ISSUE TITLE
Pass PIL/cv2 Image to Tika-Python

### ISSUE THREAD

**Issue by frederick0291** [chrismattmann/tika-python#355]
Hi,

I would like to ask if it is possible to pass an image from memory to parser?

For example I convert a pdf to an array of images in cv2. Then I apply edits into the images. 

Could I pass these images to parser? I tried but I am getting an attribute error decode. If not possible, are there other implementations that could make me do this?

What worked for me was to write the image to memory after the edits and  then open it and pass it to parser but I would like to skip this part if possible.

Thanks,
Fred.

**Comment by chrismattmann** [comment]
Interesting. See if this works after #316 (which allows objects to be passed now).
