### ISSUE TITLE
Use another augmented assignment statement

### ISSUE THREAD

**Issue by elfring** [chrismattmann/tika-python#357]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/tika/tika.py b/tika/tika.py
index 3e19b6c..8c0983d 100755
--- a/tika/tika.py
+++ b/tika/tika.py
@@ -771,7 +771,7 @@ def getRemoteFile(urlOrPath, destPath):
         return (urlOrPath, 'local')
     else:
         filename = toFilename(urlOrPath)
-        destPath = destPath + '/' + filename
+        destPath += '/' + filename
         log.info('Retrieving %s to %s.' % (urlOrPath, destPath))
         try:
             urlretrieve(urlOrPath, destPath)
```

**Comment by chrismattmann** [comment]
Sure this sounds interesting and useful. Is it back compat with other python versions? Also I'd like to see a more full patch and discussion of what benefit this provides? As it stands "improving software components" I'm not sure what the benefit is. Thanks.

**Comment by elfring** [comment]
I find that [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) can indicate also motivation for another bit of collateral evolution. :thinking:
