### ISSUE TITLE
How to use tika-python in aws lambda using docker container image

### ISSUE THREAD

**Issue by saikiranLingampalli** [chrismattmann/tika-python#369]
Hi I tried to use tika-python in **aws lambda**, using docker container image, but when I tried it is throwing error. I tried installing java. It is not working. Can anyone help me with that

**Comment by LincolnVS** [comment]
Hi, maybe I can help you. Could you show some error logs?

**Comment by chrismattmann** [comment]
Not enough detail to action here. If you provide more detail please let me/us know.
