### ISSUE TITLE
ubuntu running error

### ISSUE THREAD

**Issue by dongnizh** [chrismattmann/tika-python#37]
![f5d23fb2-d765-4cbd-9593-2f78fc6b3e2d](https://cloud.githubusercontent.com/assets/6832510/7598435/1094c57a-f8af-11e4-8595-844135b3b9f3.png)
@chrismattmann  I tried to run it on ubuntu, but it seems some syntax error on  **bad fd number**.
It probably happens because of **">&"** symbol.
Try to figure out.

**Comment by chrismattmann** [comment]
Ahh it's the shell my guess is you are using bash and not csh

**Comment by dongnizh** [comment]
![233d9883-9781-4fcb-826a-8c695f0bb6d2](https://cloud.githubusercontent.com/assets/6832510/7599219/05fa6c40-f8b5-11e4-8b5d-6962ce6647a5.png)
@chrismattmann  It is not csh. It's dash....

**Comment by chrismattmann** [comment]
Yeah >& only works for csh we need something that works across shells

**Comment by dongnizh** [comment]
Oh got it!!! Learned from you!!!

**Comment by chrismattmann** [comment]
:+1: @dongnizh - so we should figure out a cross platform solution here.

**Comment by chrismattmann** [comment]
@dongnizh check this out: http://stackoverflow.com/questions/3908063/python-subprocess-with-shell-true-redirections-and-platform-independent-subproc maybe we should use subprocess and/or popen2?

**Comment by chrismattmann** [comment]
@dongnizh did you check my link out?

**Comment by dongnizh** [comment]
@chrismattmann I would like to try to change the os cmd to subprocess and see what it is going on.

**Comment by chrismattmann** [comment]
+1 try that

**Comment by chrismattmann** [comment]
ok @dongnizh can you confirm that #41 fixed this?

**Comment by dongnizh** [comment]
@chrismattmann What do you mean? You mean the new PR?

**Comment by dongnizh** [comment]
This is closed due to #41 .

**Comment by chrismattmann** [comment]
yay thanks @dongnizh !
