### ISSUE TITLE
Using `InMemoryUploadFile` with tika. 

### ISSUE THREAD

**Issue by hamodey** [chrismattmann/tika-python#370]
Hi,

I am posting a file into my db using BE framework of Django. I would like to read the data from the file whilst parsing. 
However, I am getting the error: 

`AttributeError: 'InMemoryUploadedFile' object has no attribute 'decode'
`
I assume the issue is that the temp file that django handles differs to what tika is expecting, is there any suggestions or documentation I could have a look at?

Thanks

**Comment by chrismattmann** [comment]
tika-python doesn't directly handle object streams in parser.from_file (you have to use .from_buffer). But the latest PR I just commit in this release should address that. Thanks @hamodey
