### ISSUE TITLE
PDF Text extraction: Date superscript split into separate lines

### ISSUE THREAD

**Issue by teohsinyee** [chrismattmann/tika-python#373]
**My PDF original text screenshot:**
![image](https://user-images.githubusercontent.com/56106630/180738889-76b47696-6b4e-4cb3-b456-d3738b8b253e.png)

**Result of extraction:**
![image](https://user-images.githubusercontent.com/56106630/180738923-a1759c30-ca92-481c-9601-1d8f354ae828.png)

Is there any setting to extract the exact line as `2nd of March 2015 onwards` rather than splitting it into 3 lines?
Very much appreciated!

**Comment by chrismattmann** [comment]
I think you can do something in the upstream Tika server library. Please ask on `dev@tika.apache.org`. cc @tballison thanks @teohsinyee
