### ISSUE TITLE
Allow raw /rmeta output

### ISSUE THREAD

**Issue by tballison** [chrismattmann/tika-python#375]
The parse option uses /rmeta and then conflates all the keys together so that users can't tell which metadata goes with the primary file and which metadata goes with which embedded file.

Would it be possible to warn users of the current behavior and offer an option to get the raw json from the /rmeta endpoint?

**Comment by chrismattmann** [comment]
will test/evaluate as part of the next release (not 1.24.2 which I will release today but ) 2.6.x which I will release next week.

**Comment by chrismattmann** [comment]
Fixed in https://github.com/chrismattmann/tika-python/commit/ca2a692193307feec4277142f88fd1afd819f140
