### ISSUE TITLE
Upgrade to Tika 2.6.0

### ISSUE THREAD

**Issue by tballison** [chrismattmann/tika-python#377]

**Comment by stumpylog** [comment]
Does this library need updates to support 2.5 or is this just for updating the default value in `tika.py`?

I stumbled on this while looking at some other Tika related updates

**Comment by tballison** [comment]
In general, see:
https://cwiki.apache.org/confluence/display/TIKA/Migrating+to+Tika+2.0.0

I don't think we need to change the python code much. We'll need to change
the jars that we're calling: tika-server.X.Y.jar ->
tika-server-standard-X.Y.Z.jar, and the client will have to be robust
against the server going doing and coming back up (Tika 1.x spawnChild
becomes default in 2.x).

 There are quite a few differences in metadata, which may surprise users,
but the python wrapper doesn't care about (most?) of those.

**Comment by tballison** [comment]
Class name will also change:  org.apache.tika.server.TikaServerCli ->
org.apache.tika.server.core.TikaServerCli

There will likely be other small changes that we'll have to make as we
start the work.

**Comment by kalebmckale** [comment]
This is something we've raised before in other issues, but there hasn't been an update to this repo in over a year. I'm not sure if the fixes exist in an existing pull request or if creating a pull request would even be addressed. I'm starting to think this project might be dead, at least in its current form.

**Comment by tballison** [comment]
I was recently given access to this repo, and I'm working with a colleague to make this happen.  Should be available in a week or two.

**Comment by kalebmckale** [comment]
That's good to know. I interpreted initially as a request and not as a to-do item. I know others will be thrilled to know this, too. Thanks!

**Comment by chrismattmann** [comment]
will release this not in this next release I'm preparing today but the one following that hopefully in the next week. That will be a 2.6.x release (moving on from 1.24.2) and will likely break back compat.

**Comment by chrismattmann** [comment]
Fixed in https://github.com/chrismattmann/tika-python/commit/1d61e093ae37740a72a5fbf7506be62214b5af6d
