### ISSUE TITLE
Some Korean character not recognized

### ISSUE THREAD

**Issue by smbslt3** [chrismattmann/tika-python#378]
This is original content of pdf

![image](https://user-images.githubusercontent.com/41793074/201253766-336562d2-4e87-4ad7-a65a-43e82ae3030b.png)

and This is transcript content of the original pdf

![image](https://user-images.githubusercontent.com/41793074/201253852-eb74aaa3-9b15-4c32-9d85-c9bd3dc7a4a2.png)
![image](https://user-images.githubusercontent.com/41793074/201253884-c91aef25-427b-4a16-8d55-54431a82a005.png)

The source code is here
```python

import tika
tika.initVM()

from tika import parser
pdf_path = './EBS_기출문제/'+exams[0]
parsed = parser.from_file(pdf_path)

print(parsed['content'].strip())
```

The Korean character `"영"` not recognized by tika. It is possible that no other characters were recognized, but so far, this is the only character I have found.

There is a problem that spacing is omitted or some characters appear twice.  I can solve these problems. However, the problem of omitting certain characters is difficult to solve. 
The same problem occurs not only in this pdf but also in other pdf. Is this a problem with tika itself?

Attached below are two pdf files where this problem occurs.

[2007년_2008 대학수학능력시험_물리Ⅰ_문제.pdf](https://github.com/chrismattmann/tika-python/files/9986196/2007._2008._._.pdf)
[2022년_고3 9월 모평(평가원)_화학Ⅱ_문제.pdf](https://github.com/chrismattmann/tika-python/files/9986198/2022._.3.9._._.pdf)

**Comment by smbslt3** [comment]
`대`, `전` and `주` also not recognized

**Comment by tballison** [comment]
This is likely caused by something in the underlying Tika or PDFBox library.  See: https://github.com/chrismattmann/tika-python/issues/376#issuecomment-1299314842

**Comment by chrismattmann** [comment]
agreed. This is not an issue with tika python and is an issue with the underlying Tika or PDFBox. Please raise the issue there on their mailing lists.
