### ISSUE TITLE
flask file post handling

### ISSUE THREAD

**Issue by JGuibone** [chrismattmann/tika-python#379]
Hello,

Im wondering if someone could help me find a work around to my current use case.

basically im using flask and taking user uploaded document from post

using this code.
 
![flask-tika-01](https://user-images.githubusercontent.com/114382307/201914852-6a2e469a-2161-4f29-98f9-fa72667eb69e.PNG)

the function tikaBasedParser() is this
![flask-tika-02](https://user-images.githubusercontent.com/114382307/201912725-5ae7853e-9430-4f30-a2f0-88fe26f51551.PNG)

and the flask error page is this.
![flask-tika-03](https://user-images.githubusercontent.com/114382307/201913822-162f6f65-5d4b-4935-bd93-5201b8f11ad4.PNG)
![flask-tika-04](https://user-images.githubusercontent.com/114382307/201913848-0ab8470d-40e6-4523-b27b-79253a0be63a.PNG)

i think the reason why its bugging out is because it tika.parser doesnt like getting object as an argument.
is there another way to pass file from the code?

**Comment by chrismattmann** [comment]
You're correct, @JGuibone Currently Tika doesn't take an object in parser.from_file it takes the string filename. That said I just committed #316 which I believe will address this (give it a try). Closing but feel free to reopen if it doesn't handle that.
