### ISSUE TITLE
'charmap' codec can't decode byte 0x81 in position 279: character maps to <undefined>

### ISSUE THREAD

**Issue by MohammadFneish7** [chrismattmann/tika-python#388]
Hello, `'charmap' codec can't decode byte 0x81 in position 279: character maps to <undefined>` this happens when unpacking arabic html file with Arabic html filename. This should be please fixed in the unpack.py by adding the encoding parameter to line number 80 as follows:

`metadataFile = _text_wrapper(tarFile.extractfile(metadataMember), encoding=tarFile.encoding)`

**Comment by chrismattmann** [comment]
thanks @MohammadFneish7 can you please submit a pull request that fixes this and also provides a unit test that exposes it? Looks like a simple fix. Thank you.

**Comment by chrismattmann** [comment]
Fixed in ce7d966
