### ISSUE TITLE
Can tika extract "Marked Content" (tagged PDFs)?

### ISSUE THREAD

**Issue by MartinThoma** [chrismattmann/tika-python#393]
I've seen [PDFMarkedContentExtractor](https://pdfbox.apache.org/docs/2.0.8/javadocs/org/apache/pdfbox/text/PDFMarkedContentExtractor.html) - is this accessible by tika-python as well?

**Comment by chrismattmann** [comment]
I believe it should be... let me know if you aren't seeing it called. cc @tballison

**Comment by tballison** [comment]
That feature is still experimental in Tika and is turned off by default.  You need to turn it on via the `extractMarkedContent` parameter.  See: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=109454066

Please ask on the user list if you have any questions!  Thank you!

https://github.com/apache/tika/blob/main/README.md#mailing-lists
