### ISSUE TITLE
Need to run tika server manualy but previously it works without tika

### ISSUE THREAD

**Issue by mahmudtopu3** [chrismattmann/tika-python#400]
I had used this couple of months ago where I didn't have to configur anyhting on windows but now i need to run
this `java -jar tika-server-x.x.jar -h 0.0.0.0`  in background to run python-tika. Am i doing anything wrong?

**Comment by chrismattmann** [comment]
Can you provide more detail about what is no longer working? What are the error messages on Windows (if any?) What is present in the temporary director and the tika.log file? Can't really answer much with what you have provided @mahmudtopu3
