### ISSUE TITLE
Unable to start Tika server

### ISSUE THREAD

**Issue by kevin-guimard-ext** [chrismattmann/tika-python#402]
Hello,

I installed tika but calling the parser would systematically trigger the following error:
> RuntimeError: Unable to start Tika server.

So, I downloaded tika-server.jar and added an environment variable pointing to it as explained in the readme page, but it didn't work either.

Kevin

**Comment by nautilux2** [comment]
Hi @chrismattmann 
Same here 
This is my lambda function code
`import json
import sys; 
import os
sys.path.append('/opt/python/lib/python3.9/site-packages');
sys.path.append('/opt/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.lambda2.0.1.x86_64/jre/bin/java');

os.environ['TIKA_JAVA'] = '/opt/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.lambda2.0.1.x86_64/jre/bin/java'
os.environ['TIKA_STARTUP_SLEEP'] = '10'
os.environ['TIKA_STARTUP_MAX_RETRY'] = '10'

import tika
from tika import parser


import boto3
s3 = boto3.resource('s3')
s3client = boto3.client('s3')
BUCKET_NAME = 'demo-s3-file-bucket'
FULL_FILE_NAME = 'BB/2023104/text.txt_b6b217cf-4e90-40cc-8fa8-c0d2888dcab3'
FILE_NAME = 'text.txt_b6b217cf-4e90-40cc-8fa8-c0d2888dcab3'

def lambda_handler(event, context):
    print('init tika')
    initTika()
    print('start to read file')
    ##s3.Bucket(BUCKET_NAME).download_file(FULL_FILE_NAME, '/tmp/' + FILE_NAME)
    ##jsonOutput = parse1('text', '/tmp/' + FILE_NAME)
    ##print(jsonOutput)
    response = s3client.get_object(Bucket=BUCKET_NAME, Key=FULL_FILE_NAME)
    buffer_file = response["Body"]
    #filepath = 's3://demo-s3-file-bucket/BB/2023104/text.txt_b6b217cf-4e90-40cc-8fa8-c0d2888dcab3'  # Replace with the path of your file
    parsed_document = parser.from_buffer(buffer_file)
    print(parsed_document['content'])
    
    # TODO implement
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
def initTika():
    s3.Bucket(BUCKET_NAME).download_file('tika-server/tika-server.jar.md5', '/tmp/tika-server.jar.md5')
    s3.Bucket(BUCKET_NAME).download_file('tika-server/tika-server.jar', '/tmp/tika-server.jar')`
 
lambda python 3.9   
tika version 2.6
java version 8

all I got was 

> RuntimeError: Unable to start Tika server.
>2023-10-05T08:40:05.467Z	fbfe710b-00e7-4ab9-8993-a00a8417c929	Failed to see startup log message; retrying...
>2023-10-05 08:40:05,467 [MainThread  ] [WARNI]  Failed to see startup log message; retrying..

Can you help with this?
Thanks

**Comment by chrismattmann** [comment]
Tika-Python should start on its own. My guess is that you should look at the file you downloaded (I am guessing it's not a JAR file). Try doing `cat <file>`. Once you get the actual jar file this should work fine.
