### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by nautilux2** [chrismattmann/tika-python#403]
Hi guys
I'm using java lambda layer (https://github.com/shelfio/java-lambda-layer) that uses tika to extract text (Python runtime 3.9, tika server standard 2.6) and got this error

>    os.environ['TIKA_JAVA'] = '/opt/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.lambda2.0.1.x86_64/jre/bin'

>    "errorMessage": "[Errno 13] Permission denied: '/opt/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.lambda2.0.1.x86_64/jre/bin'",
>    "errorType": "PermissionError",

How can I resolve this?
Thank

**Comment by chrismattmann** [comment]
I think you need to ensure that you run the command `java` from your computer or reinstall it? Thanks.
