### ISSUE TITLE
pip2.7 install and setuptools install won't install __init__.py for Tika

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-python#53]
I'm stumped on this one. For whatever reason when using pip or setuptools for tika, the __init__.py for tika doesn't get installed. It complains about ``__namespace_`` packages. @nutjob4life need your help on this one.

**Comment by chrismattmann** [comment]
So this seems to have something to do with it: https://www.python.org/dev/peps/pep-0420/#rationale Hmm. Seems like __init__.py used to get installed though.

**Comment by nutjob4life** [comment]
In setup.py, delete namespace_packages. "tika" isn't a namespace package (it has other code modules in it).

**Comment by chrismattmann** [comment]
thanks @nutjob4life !
