### ISSUE TITLE
call to requests.put is blocking on Windows when using from_file

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-python#58]
{parser|detector|language|translate}.from_file all use requests.put on an open file handle to stream the file to the Tika JAX-RS server. On Windows this call freezes and doesn't return, giving eventually (correctly) a BadStatusLine return from the underlying Python httplib. Need to find out why it's blocking on requests.put on windows with streaming file handle.

**Comment by dongnizh** [comment]
@chrismattmann Is this the same as #44 ?

**Comment by dongnizh** [comment]
@chrismattmann I ran it with **tika.py parse all [filename]**, it still showed the same issue.

**Comment by chrismattmann** [comment]
Yep @dongnizh looks like the same issue any ideas? Can u try requests with a different server on windows just see if you can do a requests.put to any service

**Comment by chrismattmann** [comment]
Keeping the discussion going related to kennethreitz/requests#2725, here is what I'm seeing from the sniff:
<img width="1041" alt="screen shot 2015-08-14 at 9 13 49 pm" src="https://cloud.githubusercontent.com/assets/395887/9287451/238fdb96-42ca-11e5-9bcc-679be27f77f4.png">

**Comment by chrismattmann** [comment]
See #64 for a good enough fix for now. This is buried deep within httplib, Jetty, CXF, and other stuff.
