### ISSUE TITLE
Running server API on localhost

### ISSUE THREAD

**Issue by imclaren** [chrismattmann/tika-python#59]
If we run the tika rest server on localhost, a call such as the following will not try to use the tika rest server, but will instead attempt to download the tika jar file from http://search.maven.org ...:

parser.from_buffer(fileString, 'http://localhost:9998/tika')

The following works as expected (i.e. accesses the tika rest server on localhost):

parser.from_buffer(fileString, 'http://127.0.0.1:9998/tika')

I recommend that you either update the documentation to make this difference clear, or update the code to attempt to call the rest server on localhost before falling back to downloading the  tika jar file.

Thanks!

**Comment by chrismattmann** [comment]
thanks @imclaren I'll take a shot at fixing this.

**Comment by chrismattmann** [comment]
Can you pull https://github.com/chrismattmann/tika-python/commit/df1411f0d41bc601fa493043b4f92d62865d1990 @imclaren and see if this fixes it for you? Thanks for the report!

**Comment by imclaren** [comment]
Thanks for updating the library.  So sorry for my very tardy response.  I wanted to wait until I had the chance to pull and test the new version.  As soon as I have done so I will get back to you.  But thanks for providing and supporting this library and for your rapid response to my feature request!






—
+61 417 059 214
