### ISSUE TITLE
Recursive processing of compressed files

### ISSUE THREAD

**Issue by dziemer88** [chrismattmann/tika-python#7]
Could you please provide documentation for recursive processing of compressed files to extract both content and metadata?

**Comment by chrismattmann** [comment]
OK I need to make a simple interface as described here to fix this: http://stackoverflow.com/questions/28102943/apache-tika-1-7-parse-files-in-a-zip-archive Will get going on it this weekend.

**Comment by chrismattmann** [comment]
haven't had time to get going on this, but I am thinking about a rewrite of this library that binds to TikaJAXRS and then in turn leverages class functionality as needed. the JCC stuff makes this a pain to install.
