### ISSUE TITLE
Support to use the library i client-only mode

### ISSUE THREAD

**Issue by ghost** [chrismattmann/tika-python#71]
I think it would be useful to use the library in client-only mode. In this way the library calls a remote server and if the server is not reachable raises an exception rather than download tika and run it.
Thanks,
P.

**Comment by chrismattmann** [comment]
Hi @blakie sounds like a useful addition. Will take a look at this in the next development iteration.

**Comment by chrismattmann** [comment]
Hi @ghost if you look at [line 302](https://github.com/chrismattmann/tika-python/blob/master/tika/tika.py#L302) in tika.py you'll see that if the provided URL is localhost, it actually performs the check to see if tika is running. If it's not localhost, it simply in [line 314](https://github.com/chrismattmann/tika-python/blob/master/tika/tika.py#L314) returns the same remote URL you gave it. So it works like you desire I believe, already.
