### ISSUE TITLE
This package should work under Python 3

### ISSUE THREAD

**Issue by dtsmith2001** [chrismattmann/tika-python#73]
Please modify so it can be used in python 3.

**Comment by chrismattmann** [comment]
I don't actively use Python3 but would be happy to consider it and if you have ideas where to modify it let me know.

**Comment by dtsmith2001** [comment]
My problem is with

from tika import config

The error message is getConfig can't be loaded. Here are the details.

[emailzone] C:\Users\dsmith\Downloads>python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Dec  1 2015, 11:39:45) [MSC v
.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tika
>>> from tika import config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\emailzone\lib\site-packages\tika\config.py", line 19,
in <module>
    from tika import getConfig
ImportError: cannot import name 'getConfig'

Dale Smith, Ph.D.
Data Scientist
Nexidia
________________________________

**Comment by chrismattmann** [comment]
thanks @dtsmith2001 as I said, I don't normally use/test with Python3 and the library right now is actively used and tested with Python2.7. I'm happy to look into this but won't have too many cycles (and test environments) set up to make progress here. If you are a Python3 user, which it seems you are, would you have some time to look into why it's not working? Looking at #68 there were some suggestions there.

**Comment by fiacre** [comment]
I have a python3 version that passes all tests:  https://github.com/fiacre/tika-python 

I started working on backporting, but may not have too much time.  Please check back

**Comment by chrismattmann** [comment]
Thanks @fiacre is it back compat with Python 2.7?

**Comment by fiacre** [comment]
I am not done testing, but I have made the effort to make it backwards compatible.  I expect to have it tested for 2.7 and 3.5 within a few days.  I'll make a pull request.

**Comment by chrismattmann** [comment]
fixed in #75 and #84
