### ISSUE TITLE
Mix of spaces in tabs in tika.py

### ISSUE THREAD

**Issue by fiacre** [chrismattmann/tika-python#83]
$ git clone https://github.com/chrismattmann/tika-python.git
$ cd tika-python/tika/
$ python tika.py 
  File "tika.py", line 94
    """
      ^
IndentationError: expected an indented block

**Comment by fysteven** [comment]
Hi there,

I just checked and it works for me. You might want to git clone the latest version and try again.

Thanks,
Yao

**Comment by chrismattmann** [comment]
yep works fine? @fiacre please re-open if you are still having the issue.
