### ISSUE TITLE
New commits are breaking Python 3 compatibility

### ISSUE THREAD

**Issue by Pehat** [chrismattmann/tika-python#85]
I've put some effort to make `tika-python` compatible with Python 3, but in new commits I see something like this:
```print resp```
So if you want to keep `tika-python` compatible with Python 3, all the contributors should come to the agreement about coding style. Let alone that modules should not print anything - the user of the library may not be willing to have this stuff in one's program output. Debugging info should be properly logged (with the help of `logging` module, for example). Please, @chrismattmann, @yashtanna93, @karanjeets, @kdurril, @dongnizh, think about it.
It's also would be great to use automated testing with [Tox](https://tox.readthedocs.org/en/latest/) and [Travis CI](https://travis-ci.org/). The former allows you to set up multiple Python environments for testing while the second allows you to see which of the new commits/pull requests are violating existing tests. Let's build a better software!

**Comment by kdurril** [comment]
Helli Chris,  Renat has good points. TOX is a good tool for  testing for
the reasons Renat specified. It is a lot of work to remind users to
consider both 2 and 3. Renat should write the test suite and monitor for
compatibility.

Thanks for all of the work you all do.

**Comment by Pehat** [comment]
Thanks for you support, @kdurril ! Honestly, I haven't used it before but now I've made some copypastes from the cheat sheet and executed tests from `tika/tests` on my fork of `tika-python`. Wow, it's really easy to turn on continuous integration! [You can see](https://travis-ci.org/Pehat/tika-python/builds/119023181) that Python 2 passes the test and Python 3 fails.

**Comment by chrismattmann** [comment]
What new commits are you talking about @Pehat ?

**Comment by chrismattmann** [comment]
there are the only commits since I merged your PR: f79e3420d5b0751202fd73e574cb2d3c7ac08a0e, 443e982b4dc81055774d898e99a9af145291a393 and ad9a883505f7377b0b9120f7110b25f9e1f49eb6

**Comment by chrismattmann** [comment]
@Pehat I'm totally open to TravisCI and/or Tox too whichever one makes sense.

**Comment by yashtanna93** [comment]
@Pehat  @chrismattmann  I don't know about the 'print resp'. And the other echo2 error is because the unicode is not specified. I have fixed both the errors and pushed them. Please review it before merging it. Also I test results using travis could be found [here](https://travis-ci.org/yashtanna93/tika-python/builds/119154383) for the commit

**Comment by Pehat** [comment]
@yashtanna93 thank you for your fixes! I've seen [this commit](https://github.com/chrismattmann/tika-python/commit/beea1fdce9c85590c5f8679c97665dc0ee373ed1) so I've decided that it's was your edit. On the second thought, I've found that I've overlooked this line in my own fixes so it should be my fault. Thank you for running the tests.
@chrismattmann I'm glad to see you supporting the idea. Merging with @yashtanna93 's PR should integrate Travis CI into your repository.

**Comment by yashtanna93** [comment]
@Pehat it was your commit which has made the change
take a look [here](https://github.com/chrismattmann/tika-python/commit/c73d669a81c6997a68c56db0d072fb67d5694cd0)

I didn't get your point about the codec thing because it should define which codec is used which is done using string.

**Comment by Pehat** [comment]
@yashtanna93 let's discuss the codec in the PR topic so we won't mix up the different things in the single thread.

About `print resp` : as I said before, I've overlooked this line when I've made my partial fix for Python 3 and then merged with @chrismattmann 's master branch. It's definitely a mistake and I apologize for the bad merge and false accusations.

**Comment by chrismattmann** [comment]
this is fixed in #87
