### ISSUE TITLE
Support Tika's `fileUrl` option

### ISSUE THREAD

**Issue by torfsen** [chrismattmann/tika-python#88]
tika-server supports the [`fileUrl` option](https://wiki.apache.org/tika/TikaJAXRS#Extracting_A_Document_From_A_URL) that lets you extract data from a file available via an URL. This is very useful if the Tika server runs on host A, the file is located on host B and the program using Tika is running on host C. Without `fileUrl`, one first has to transfer the file from host B to host C and then transfer it to host A. With `fileUrl` one can tell Tika to directly transfer the file from host B to host A.

tika-python should support this feature, for example like this:

    parsed = tika.parser.from_url('http://example.com/my_document')

**Comment by chrismattmann** [comment]
great @torfsen do you have time for a PR for this?

**Comment by torfsen** [comment]
@chrismattmann I will look into it but can't promise anything at the moment.

**Comment by torfsen** [comment]
Actually, does Tika really support `fileUrl` at the moment, @chrismattmann?

I tried to get it to work but couldn't and then I found [this issue](https://issues.apache.org/jira/browse/TIKA-1690) where [a comment](https://issues.apache.org/jira/browse/TIKA-1690?focusedCommentId=14640134&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14640134) says that the commit that added the `fileUrl` feature was reverted. Also, [searching for `fileUrl` in the code](https://github.com/apache/tika/search?utf8=%E2%9C%93&q=fileurl) yields no results. Similarly, `fileUrl` [is not mentioned in the current API documentation](https://www.google.com/search?hl=de&as_q=fileurl&as_epq=&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=https%3A%2F%2Ftika.apache.org%2F1.12%2Fapi%2F&as_occt=any&safe=images&as_filetype=&as_rights=).

Unfortunately the [page where I read about the feature](https://wiki.apache.org/tika/TikaJAXRS#Extracting_A_Document_From_A_URL) doesn't specify any Tika version at all.

**Comment by chrismattmann** [comment]
Yeah @torfsen forgot about that there is a [CVE](https://mail-archives.apache.org/mod_mbox/tika-user/201508.mbox/%3CB7848C4E-BC38-4477-832E-B1138B83195A@apache.org%3E) about this and we took the support out from Tika since it can all remote access to local (`file://`) files.

**Comment by torfsen** [comment]
OK, thanks for the clarification!
