### ISSUE TITLE
CLI plaintext output misbehaviour when using installer

### ISSUE THREAD

**Issue by bitsgalore** [chrismattmann/tika-python#99]
I installed tika-python using pip, and then ran it in detect mode on all files in a directory using the following command:

```
tika-python/tika $ tika-python detect type /home/johan/epub-CB/20150505/* >~/stdout.txt 2> ~/stderr.txt
```

Result stdout.txt:

```
('server endpoint:', 'http://localhost:9998')
('server endpoint:', 'http://localhost:9998')
('server endpoint:', 'http://localhost:9998')
('server endpoint:', 'http://localhost:9998')
... etc ..
```

Result stderr.txt:

```
[(200, u'application/epub+zip'), (200, u'application/epub+zip'), (200, u'application/epub+zip'), (200, u'application/epub+zip'), ...
```

So instead of printing the mimetype strings as plain text, it actually prints a dump of the internal Python objects (moreover they're printed to stderr, where I would expect stdout)! I then cloned the repo and ran `tika.py` directly without using the installer (same command line options):

```
python tika.py detect type /home/johan/epub-CB/20150505/* > ~/stdout.txt 2> ~/stderr.txt
```

Result stdout.txt:

```
application/epub+zip
application/epub+zip
application/epub+zip
application/epub+zip
application/epub+zip
application/epub+zip
application/epub+zip
 ...etc.
```

Result stderr.txt: empty file.

Which is the expected behaviour. So it seems something gets broken in the install process.

**Comment by chrismattmann** [comment]
hi @bitsgalore interesting problem. I'll investigate. I would imagine in the meanwhile you have a good workaround and/or you can call it from python directly or in a script.

**Comment by chrismattmann** [comment]
@brianwilson1 can you help here

**Comment by yashtanna93** [comment]
@chrismattmann it looks like pip is not updated with the latest commits done on github. I tried it with pip sources and I got those statements but not when I built it with sources on github.

**Comment by yashtanna93** [comment]
@bitsgalore I am not able to recreate the issue. Does it still exist?

**Comment by chrismattmann** [comment]
I'm not sure if I see it @yashtanna93 Hey @bitsgalore can you confirm it's still there?

**Comment by bitsgalore** [comment]
I just uninstalled tika-python and then tried to re-install using:

    sudo pip install tika --upgrade

But after running this, I don't see any trace of `tika-python` in `/usr/local/bin/` (didn't have this problem before). 

Not sure if this is relevant at all but during the install process I got the following messages:

      Found existing installation: setuptools 3.3
        Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
      Found existing installation: requests 2.2.1
        Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS

So I imagine this might be some conflict between the setup.py and pip installs.

**Comment by chrismattmann** [comment]
hrm @bitsgalore you may need to rm -rf tika from site-packages and then try to reinstall..

**Comment by chrismattmann** [comment]
not sure this is still an issue, so closing it.
